apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: live-auction
resources:
  - namespace.yaml
  - runtime-config.yaml
  - service-accounts.yaml
  - services.yaml
  - migrate-job.yaml
  - workloads.yaml
  - availability.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: live-auction
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
