apiVersion: v1
kind: Namespace
metadata:
  name: live-auction
  labels:
    app.kubernetes.io/name: live-auction
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
