apiVersion: v1
kind: ServiceAccount
metadata:
  name: auction-gateway
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auction-service
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auction-worker
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auction-migrate
automountServiceAccountToken: false
