// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v4.25.8
// source: auction/service/v1/auction.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAuctionServiceCancelLot = "/auction.service.v1.AuctionService/CancelLot"
const OperationAuctionServiceConsultBuyer = "/auction.service.v1.AuctionService/ConsultBuyer"
const OperationAuctionServiceCreateLot = "/auction.service.v1.AuctionService/CreateLot"
const OperationAuctionServiceCreateLotDraft = "/auction.service.v1.AuctionService/CreateLotDraft"
const OperationAuctionServiceGetLot = "/auction.service.v1.AuctionService/GetLot"
const OperationAuctionServiceGetLotResultView = "/auction.service.v1.AuctionService/GetLotResultView"
const OperationAuctionServiceGetRoomPersonalState = "/auction.service.v1.AuctionService/GetRoomPersonalState"
const OperationAuctionServiceGetRoomPresence = "/auction.service.v1.AuctionService/GetRoomPresence"
const OperationAuctionServiceGetRoomSnapshot = "/auction.service.v1.AuctionService/GetRoomSnapshot"
const OperationAuctionServiceListAdminAuctionOrders = "/auction.service.v1.AuctionService/ListAdminAuctionOrders"
const OperationAuctionServiceListAdminLotPage = "/auction.service.v1.AuctionService/ListAdminLotPage"
const OperationAuctionServiceListAdminRoomList = "/auction.service.v1.AuctionService/ListAdminRoomList"
const OperationAuctionServiceListBuyerSuggestions = "/auction.service.v1.AuctionService/ListBuyerSuggestions"
const OperationAuctionServiceListLots = "/auction.service.v1.AuctionService/ListLots"
const OperationAuctionServiceListMyAuctionOrders = "/auction.service.v1.AuctionService/ListMyAuctionOrders"
const OperationAuctionServiceListMyBidRecords = "/auction.service.v1.AuctionService/ListMyBidRecords"
const OperationAuctionServiceListPublicRoomList = "/auction.service.v1.AuctionService/ListPublicRoomList"
const OperationAuctionServiceListRoomEvents = "/auction.service.v1.AuctionService/ListRoomEvents"
const OperationAuctionServicePatchLotDraft = "/auction.service.v1.AuctionService/PatchLotDraft"
const OperationAuctionServicePlaceBid = "/auction.service.v1.AuctionService/PlaceBid"
const OperationAuctionServiceQueueLot = "/auction.service.v1.AuctionService/QueueLot"
const OperationAuctionServiceRevealTrustCard = "/auction.service.v1.AuctionService/RevealTrustCard"
const OperationAuctionServiceSettleLot = "/auction.service.v1.AuctionService/SettleLot"
const OperationAuctionServiceStartDuel = "/auction.service.v1.AuctionService/StartDuel"
const OperationAuctionServiceStartLot = "/auction.service.v1.AuctionService/StartLot"

type AuctionServiceHTTPServer interface {
	// CancelLot 主播异常取消拍品。
	//
	// 调用方：主播端/运营端。
	// 状态流转：LIVE -> CANCELLED。
	// 服务端动作：记录取消原因，并广播 LOT_CANCELLED。
	CancelLot(context.Context, *CancelLotRequest) (*CancelLotReply, error)
	// ConsultBuyer 买家找拍品助手。
	//
	// 调用方：观众端。
	// 用途：根据用户输入的品类、预算或用途，返回公开可见的候选竞拍拍品。
	// 注意：这里只做找拍品和来源解释，不返回出价建议。
	ConsultBuyer(context.Context, *BuyerConsultRequest) (*BuyerConsultReply, error)
	// CreateLot 创建拍品草稿。
	//
	// 调用方：主播端/运营端。
	// 输入：直播间 ID、商品基础信息、竞拍规则、信任揭示卡片。
	// 输出：状态为 DRAFT 的拍品。
	// 注意：创建后还没有开拍，观众不能出价。
	CreateLot(context.Context, *CreateLotRequest) (*CreateLotReply, error)
	// CreateLotDraft 创建空草稿。用于添加拍品页初始化自动保存容器，允许商品资料和竞拍规则为空。
	CreateLotDraft(context.Context, *CreateLotRequest) (*CreateLotReply, error)
	// GetLot 查询拍品详情。
	//
	// 调用方：主播端、观众端、调试工具。
	// 用途：查询某个拍品当前完整状态，包括当前价、领先者、玩法状态等。
	GetLot(context.Context, *GetLotRequest) (*GetLotReply, error)
	// GetLotResultView 查询拍品结果。
	GetLotResultView(context.Context, *GetLotResultRequest) (*GetLotResultReply, error)
	// GetRoomPersonalState 获取当前买家在房间当前版本上的私有覆盖状态。
	//
	// 调用方：已登录观众端。
	// 用途：私人 WebSocket 增量丢失、订单仍在投影时，只恢复当前用户状态。
	GetRoomPersonalState(context.Context, *GetRoomPersonalStateRequest) (*GetRoomPersonalStateReply, error)
	// GetRoomPresence 获取直播间在线状态。
	//
	// 调用方：主播端/运营端。
	// 用途：工作台展示当前房间 WebSocket 真实连接情况。
	GetRoomPresence(context.Context, *GetRoomPresenceRequest) (*GetRoomPresenceReply, error)
	// GetRoomSnapshot 获取直播间权威快照。
	//
	// 调用方：观众端。
	// 用途：首次进入直播间、WebSocket 重连、前端状态不可信时，用它恢复当前状态。
	GetRoomSnapshot(context.Context, *GetRoomSnapshotRequest) (*GetRoomSnapshotReply, error)
	// ListAdminAuctionOrders 查询后台竞拍订单。
	ListAdminAuctionOrders(context.Context, *ListAuctionOrdersRequest) (*ListAuctionOrdersReply, error)
	// ListAdminLotPage 查询后台拍品。
	ListAdminLotPage(context.Context, *ListAdminLotPageRequest) (*ListAdminLotPageReply, error)
	// ListAdminRoomList 查询后台房间。
	ListAdminRoomList(context.Context, *ListAdminRoomsRequest) (*ListRoomsReply, error)
	// ListBuyerSuggestions 获取买家推荐搜索词。
	ListBuyerSuggestions(context.Context, *ListBuyerSuggestionsRequest) (*ListBuyerSuggestionsReply, error)
	// ListLots 查询直播间拍品列表。
	//
	// 调用方：主播端/运营端。
	// 用途：查看某个直播间下的草稿、竞拍中、已成交拍品。
	// V1 可以先只返回少量数据，分页字段为后续预留。
	ListLots(context.Context, *ListLotsRequest) (*ListLotsReply, error)
	// ListMyAuctionOrders 查询当前买家的竞拍订单。
	ListMyAuctionOrders(context.Context, *ListAuctionOrdersRequest) (*ListAuctionOrdersReply, error)
	// ListMyBidRecords 查询当前买家的出价记录。
	ListMyBidRecords(context.Context, *ListBidRecordsRequest) (*ListBidRecordsReply, error)
	// ListPublicRoomList 查询公开房间。
	ListPublicRoomList(context.Context, *ListPublicRoomsRequest) (*ListPublicRoomsReply, error)
	// ListRoomEvents 查询直播间最近事件。
	//
	// 调用方：主播端/运营端。
	// 用途：工作台恢复最近出价、开拍、成交、取消、支付等操作日志。
	ListRoomEvents(context.Context, *ListRoomEventsRequest) (*ListRoomEventsReply, error)
	// PatchLotDraft 静默保存草稿。用于添加拍品页自动保存，允许部分字段更新。
	PatchLotDraft(context.Context, *PatchLotDraftRequest) (*PatchLotDraftReply, error)
	// PlaceBid 出价。
	//
	// 调用方：观众端。
	// 服务端需要校验：
	// - 拍品是否存在；
	// - 拍品是否处于 LIVE；
	// - 是否已经超时；
	// - 出价是否大于等于 current_price + min_increment；
	// - 幂等键是否重复。
	// 成功后广播 BID_ACCEPTED、LOT_UPDATED、RANKING_UPDATED。
	PlaceBid(context.Context, *PlaceBidRequest) (*PlaceBidReply, error)
	// QueueLot 加入本场队列。用于添加拍品页唯一主动作，成功后仍不直接开拍。
	QueueLot(context.Context, *QueueLotRequest) (*QueueLotReply, error)
	// RevealTrustCard 主播揭示信任卡片。
	//
	// 调用方：主播端/运营端。
	// 用途：在竞拍过程中展示证书、瑕疵、细节图、售后承诺等信息。
	// 这是 V1 体现“非标品信任建立”的核心玩法。
	RevealTrustCard(context.Context, *RevealTrustCardRequest) (*RevealTrustCardReply, error)
	// SettleLot 落锤成交。
	//
	// 调用方：主播端/运营端，后续也可以由定时任务自动触发。
	// 状态流转：LIVE -> SETTLED。
	// 服务端动作：锁定 winner、final_price、settled_at，并广播 LOT_SETTLED。
	SettleLot(context.Context, *SettleLotRequest) (*SettleLotReply, error)
	// StartDuel 进入双人巅峰竞拍模式。
	//
	// 调用方：主播端/运营端，后续也可以由规则引擎自动触发。
	// 用途：最后阶段强化 Top2 竞价展示，制造直播间竞技感。
	// V1 注意：Duel Mode 只是展示强化，不禁止其他观众继续合法出价。
	StartDuel(context.Context, *StartDuelRequest) (*StartDuelReply, error)
	// StartLot 开拍。
	//
	// 调用方：主播端/运营端。
	// 状态流转：DRAFT -> LIVE。
	// 服务端动作：设置 started_at、ends_at、current_price，并广播 LOT_STARTED。
	StartLot(context.Context, *StartLotRequest) (*StartLotReply, error)
}

func RegisterAuctionServiceHTTPServer(s *http.Server, srv AuctionServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/lots", _AuctionService_CreateLot0_HTTP_Handler(srv))
	r.POST("/api/lots/drafts", _AuctionService_CreateLotDraft0_HTTP_Handler(srv))
	r.PATCH("/api/lots/{lot_id}/draft", _AuctionService_PatchLotDraft0_HTTP_Handler(srv))
	r.POST("/api/lots/{lot_id}/queue", _AuctionService_QueueLot0_HTTP_Handler(srv))
	r.GET("/api/lots/{lot_id}", _AuctionService_GetLot0_HTTP_Handler(srv))
	r.GET("/api/lots", _AuctionService_ListLots0_HTTP_Handler(srv))
	r.POST("/api/lots/{lot_id}/start", _AuctionService_StartLot0_HTTP_Handler(srv))
	r.POST("/api/lots/{lot_id}/bid", _AuctionService_PlaceBid0_HTTP_Handler(srv))
	r.POST("/api/lots/{lot_id}/trust-cards/{card_id}/reveal", _AuctionService_RevealTrustCard0_HTTP_Handler(srv))
	r.POST("/api/lots/{lot_id}/duel", _AuctionService_StartDuel0_HTTP_Handler(srv))
	r.POST("/api/lots/{lot_id}/settle", _AuctionService_SettleLot0_HTTP_Handler(srv))
	r.POST("/api/lots/{lot_id}/cancel", _AuctionService_CancelLot0_HTTP_Handler(srv))
	r.GET("/api/rooms/{room_id}/snapshot", _AuctionService_GetRoomSnapshot0_HTTP_Handler(srv))
	r.GET("/api/rooms/{room_id}/presence", _AuctionService_GetRoomPresence0_HTTP_Handler(srv))
	r.GET("/api/rooms/{room_id}/events", _AuctionService_ListRoomEvents0_HTTP_Handler(srv))
	r.GET("/api/lots/{lot_id}/result", _AuctionService_GetLotResultView0_HTTP_Handler(srv))
	r.GET("/api/me/orders", _AuctionService_ListMyAuctionOrders0_HTTP_Handler(srv))
	r.GET("/api/me/bids", _AuctionService_ListMyBidRecords0_HTTP_Handler(srv))
	r.GET("/api/admin/orders", _AuctionService_ListAdminAuctionOrders0_HTTP_Handler(srv))
	r.GET("/api/admin/lots", _AuctionService_ListAdminLotPage0_HTTP_Handler(srv))
	r.GET("/api/admin/rooms", _AuctionService_ListAdminRoomList0_HTTP_Handler(srv))
	r.GET("/api/rooms", _AuctionService_ListPublicRoomList0_HTTP_Handler(srv))
	r.GET("/api/ai/buyer/suggestions", _AuctionService_ListBuyerSuggestions0_HTTP_Handler(srv))
	r.POST("/api/ai/buyer/consult", _AuctionService_ConsultBuyer0_HTTP_Handler(srv))
	r.GET("/api/rooms/{room_id}/me", _AuctionService_GetRoomPersonalState0_HTTP_Handler(srv))
}

func _AuctionService_CreateLot0_HTTP_Handler(srv AuctionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateLotRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuctionServiceCreateLot)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateLot(ctx, req.(*CreateLotRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateLotReply)
		return ctx.Result(200, reply)
	}
}

func _AuctionService_CreateLotDraft0_HTTP_Handler(srv AuctionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateLotRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuctionServiceCreateLotDraft)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateLotDraft(ctx, req.(*CreateLotRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateLotReply)
		return ctx.Result(200, reply)
	}
}

func _AuctionService_PatchLotDraft0_HTTP_Handler(srv AuctionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PatchLotDraftRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuctionServicePatchLotDraft)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PatchLotDraft(ctx, req.(*PatchLotDraftRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PatchLotDraftReply)
		return ctx.Result(200, reply)
	}
}

func _AuctionService_QueueLot0_HTTP_Handler(srv AuctionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in QueueLotRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuctionServiceQueueLot)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.QueueLot(ctx, req.(*QueueLotRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*QueueLotReply)
		return ctx.Result(200, reply)
	}
}

func _AuctionService_GetLot0_HTTP_Handler(srv AuctionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetLotRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuctionServiceGetLot)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetLot(ctx, req.(*GetLotRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetLotReply)
		return ctx.Result(200, reply)
	}
}

func _AuctionService_ListLots0_HTTP_Handler(srv AuctionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListLotsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuctionServiceListLots)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListLots(ctx, req.(*ListLotsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListLotsReply)
		return ctx.Result(200, reply)
	}
}

func _AuctionService_StartLot0_HTTP_Handler(srv AuctionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in StartLotRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuctionServiceStartLot)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.StartLot(ctx, req.(*StartLotRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*StartLotReply)
		return ctx.Result(200, reply)
	}
}

func _AuctionService_PlaceBid0_HTTP_Handler(srv AuctionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PlaceBidRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuctionServicePlaceBid)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PlaceBid(ctx, req.(*PlaceBidRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PlaceBidReply)
		return ctx.Result(200, reply)
	}
}

func _AuctionService_RevealTrustCard0_HTTP_Handler(srv AuctionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RevealTrustCardRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuctionServiceRevealTrustCard)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RevealTrustCard(ctx, req.(*RevealTrustCardRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RevealTrustCardReply)
		return ctx.Result(200, reply)
	}
}

func _AuctionService_StartDuel0_HTTP_Handler(srv AuctionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in StartDuelRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuctionServiceStartDuel)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.StartDuel(ctx, req.(*StartDuelRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*StartDuelReply)
		return ctx.Result(200, reply)
	}
}

func _AuctionService_SettleLot0_HTTP_Handler(srv AuctionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SettleLotRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuctionServiceSettleLot)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SettleLot(ctx, req.(*SettleLotRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SettleLotReply)
		return ctx.Result(200, reply)
	}
}

func _AuctionService_CancelLot0_HTTP_Handler(srv AuctionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CancelLotRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuctionServiceCancelLot)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CancelLot(ctx, req.(*CancelLotRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CancelLotReply)
		return ctx.Result(200, reply)
	}
}

func _AuctionService_GetRoomSnapshot0_HTTP_Handler(srv AuctionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetRoomSnapshotRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuctionServiceGetRoomSnapshot)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRoomSnapshot(ctx, req.(*GetRoomSnapshotRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetRoomSnapshotReply)
		return ctx.Result(200, reply)
	}
}

func _AuctionService_GetRoomPresence0_HTTP_Handler(srv AuctionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetRoomPresenceRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuctionServiceGetRoomPresence)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRoomPresence(ctx, req.(*GetRoomPresenceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetRoomPresenceReply)
		return ctx.Result(200, reply)
	}
}

func _AuctionService_ListRoomEvents0_HTTP_Handler(srv AuctionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListRoomEventsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuctionServiceListRoomEvents)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListRoomEvents(ctx, req.(*ListRoomEventsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListRoomEventsReply)
		return ctx.Result(200, reply)
	}
}

func _AuctionService_GetLotResultView0_HTTP_Handler(srv AuctionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetLotResultRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuctionServiceGetLotResultView)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetLotResultView(ctx, req.(*GetLotResultRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetLotResultReply)
		return ctx.Result(200, reply)
	}
}

func _AuctionService_ListMyAuctionOrders0_HTTP_Handler(srv AuctionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAuctionOrdersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuctionServiceListMyAuctionOrders)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMyAuctionOrders(ctx, req.(*ListAuctionOrdersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAuctionOrdersReply)
		return ctx.Result(200, reply)
	}
}

func _AuctionService_ListMyBidRecords0_HTTP_Handler(srv AuctionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListBidRecordsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuctionServiceListMyBidRecords)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMyBidRecords(ctx, req.(*ListBidRecordsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListBidRecordsReply)
		return ctx.Result(200, reply)
	}
}

func _AuctionService_ListAdminAuctionOrders0_HTTP_Handler(srv AuctionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAuctionOrdersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuctionServiceListAdminAuctionOrders)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAdminAuctionOrders(ctx, req.(*ListAuctionOrdersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAuctionOrdersReply)
		return ctx.Result(200, reply)
	}
}

func _AuctionService_ListAdminLotPage0_HTTP_Handler(srv AuctionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAdminLotPageRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuctionServiceListAdminLotPage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAdminLotPage(ctx, req.(*ListAdminLotPageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAdminLotPageReply)
		return ctx.Result(200, reply)
	}
}

func _AuctionService_ListAdminRoomList0_HTTP_Handler(srv AuctionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAdminRoomsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuctionServiceListAdminRoomList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAdminRoomList(ctx, req.(*ListAdminRoomsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListRoomsReply)
		return ctx.Result(200, reply)
	}
}

func _AuctionService_ListPublicRoomList0_HTTP_Handler(srv AuctionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListPublicRoomsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuctionServiceListPublicRoomList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListPublicRoomList(ctx, req.(*ListPublicRoomsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListPublicRoomsReply)
		return ctx.Result(200, reply)
	}
}

func _AuctionService_ListBuyerSuggestions0_HTTP_Handler(srv AuctionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListBuyerSuggestionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuctionServiceListBuyerSuggestions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListBuyerSuggestions(ctx, req.(*ListBuyerSuggestionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListBuyerSuggestionsReply)
		return ctx.Result(200, reply)
	}
}

func _AuctionService_ConsultBuyer0_HTTP_Handler(srv AuctionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BuyerConsultRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuctionServiceConsultBuyer)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ConsultBuyer(ctx, req.(*BuyerConsultRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BuyerConsultReply)
		return ctx.Result(200, reply)
	}
}

func _AuctionService_GetRoomPersonalState0_HTTP_Handler(srv AuctionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetRoomPersonalStateRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuctionServiceGetRoomPersonalState)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRoomPersonalState(ctx, req.(*GetRoomPersonalStateRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetRoomPersonalStateReply)
		return ctx.Result(200, reply)
	}
}

type AuctionServiceHTTPClient interface {
	// CancelLot 主播异常取消拍品。
	//
	// 调用方：主播端/运营端。
	// 状态流转：LIVE -> CANCELLED。
	// 服务端动作：记录取消原因，并广播 LOT_CANCELLED。
	CancelLot(ctx context.Context, req *CancelLotRequest, opts ...http.CallOption) (rsp *CancelLotReply, err error)
	// ConsultBuyer 买家找拍品助手。
	//
	// 调用方：观众端。
	// 用途：根据用户输入的品类、预算或用途，返回公开可见的候选竞拍拍品。
	// 注意：这里只做找拍品和来源解释，不返回出价建议。
	ConsultBuyer(ctx context.Context, req *BuyerConsultRequest, opts ...http.CallOption) (rsp *BuyerConsultReply, err error)
	// CreateLot 创建拍品草稿。
	//
	// 调用方：主播端/运营端。
	// 输入：直播间 ID、商品基础信息、竞拍规则、信任揭示卡片。
	// 输出：状态为 DRAFT 的拍品。
	// 注意：创建后还没有开拍，观众不能出价。
	CreateLot(ctx context.Context, req *CreateLotRequest, opts ...http.CallOption) (rsp *CreateLotReply, err error)
	// CreateLotDraft 创建空草稿。用于添加拍品页初始化自动保存容器，允许商品资料和竞拍规则为空。
	CreateLotDraft(ctx context.Context, req *CreateLotRequest, opts ...http.CallOption) (rsp *CreateLotReply, err error)
	// GetLot 查询拍品详情。
	//
	// 调用方：主播端、观众端、调试工具。
	// 用途：查询某个拍品当前完整状态，包括当前价、领先者、玩法状态等。
	GetLot(ctx context.Context, req *GetLotRequest, opts ...http.CallOption) (rsp *GetLotReply, err error)
	// GetLotResultView 查询拍品结果。
	GetLotResultView(ctx context.Context, req *GetLotResultRequest, opts ...http.CallOption) (rsp *GetLotResultReply, err error)
	// GetRoomPersonalState 获取当前买家在房间当前版本上的私有覆盖状态。
	//
	// 调用方：已登录观众端。
	// 用途：私人 WebSocket 增量丢失、订单仍在投影时，只恢复当前用户状态。
	GetRoomPersonalState(ctx context.Context, req *GetRoomPersonalStateRequest, opts ...http.CallOption) (rsp *GetRoomPersonalStateReply, err error)
	// GetRoomPresence 获取直播间在线状态。
	//
	// 调用方：主播端/运营端。
	// 用途：工作台展示当前房间 WebSocket 真实连接情况。
	GetRoomPresence(ctx context.Context, req *GetRoomPresenceRequest, opts ...http.CallOption) (rsp *GetRoomPresenceReply, err error)
	// GetRoomSnapshot 获取直播间权威快照。
	//
	// 调用方：观众端。
	// 用途：首次进入直播间、WebSocket 重连、前端状态不可信时，用它恢复当前状态。
	GetRoomSnapshot(ctx context.Context, req *GetRoomSnapshotRequest, opts ...http.CallOption) (rsp *GetRoomSnapshotReply, err error)
	// ListAdminAuctionOrders 查询后台竞拍订单。
	ListAdminAuctionOrders(ctx context.Context, req *ListAuctionOrdersRequest, opts ...http.CallOption) (rsp *ListAuctionOrdersReply, err error)
	// ListAdminLotPage 查询后台拍品。
	ListAdminLotPage(ctx context.Context, req *ListAdminLotPageRequest, opts ...http.CallOption) (rsp *ListAdminLotPageReply, err error)
	// ListAdminRoomList 查询后台房间。
	ListAdminRoomList(ctx context.Context, req *ListAdminRoomsRequest, opts ...http.CallOption) (rsp *ListRoomsReply, err error)
	// ListBuyerSuggestions 获取买家推荐搜索词。
	ListBuyerSuggestions(ctx context.Context, req *ListBuyerSuggestionsRequest, opts ...http.CallOption) (rsp *ListBuyerSuggestionsReply, err error)
	// ListLots 查询直播间拍品列表。
	//
	// 调用方：主播端/运营端。
	// 用途：查看某个直播间下的草稿、竞拍中、已成交拍品。
	// V1 可以先只返回少量数据，分页字段为后续预留。
	ListLots(ctx context.Context, req *ListLotsRequest, opts ...http.CallOption) (rsp *ListLotsReply, err error)
	// ListMyAuctionOrders 查询当前买家的竞拍订单。
	ListMyAuctionOrders(ctx context.Context, req *ListAuctionOrdersRequest, opts ...http.CallOption) (rsp *ListAuctionOrdersReply, err error)
	// ListMyBidRecords 查询当前买家的出价记录。
	ListMyBidRecords(ctx context.Context, req *ListBidRecordsRequest, opts ...http.CallOption) (rsp *ListBidRecordsReply, err error)
	// ListPublicRoomList 查询公开房间。
	ListPublicRoomList(ctx context.Context, req *ListPublicRoomsRequest, opts ...http.CallOption) (rsp *ListPublicRoomsReply, err error)
	// ListRoomEvents 查询直播间最近事件。
	//
	// 调用方：主播端/运营端。
	// 用途：工作台恢复最近出价、开拍、成交、取消、支付等操作日志。
	ListRoomEvents(ctx context.Context, req *ListRoomEventsRequest, opts ...http.CallOption) (rsp *ListRoomEventsReply, err error)
	// PatchLotDraft 静默保存草稿。用于添加拍品页自动保存，允许部分字段更新。
	PatchLotDraft(ctx context.Context, req *PatchLotDraftRequest, opts ...http.CallOption) (rsp *PatchLotDraftReply, err error)
	// PlaceBid 出价。
	//
	// 调用方：观众端。
	// 服务端需要校验：
	// - 拍品是否存在；
	// - 拍品是否处于 LIVE；
	// - 是否已经超时；
	// - 出价是否大于等于 current_price + min_increment；
	// - 幂等键是否重复。
	// 成功后广播 BID_ACCEPTED、LOT_UPDATED、RANKING_UPDATED。
	PlaceBid(ctx context.Context, req *PlaceBidRequest, opts ...http.CallOption) (rsp *PlaceBidReply, err error)
	// QueueLot 加入本场队列。用于添加拍品页唯一主动作，成功后仍不直接开拍。
	QueueLot(ctx context.Context, req *QueueLotRequest, opts ...http.CallOption) (rsp *QueueLotReply, err error)
	// RevealTrustCard 主播揭示信任卡片。
	//
	// 调用方：主播端/运营端。
	// 用途：在竞拍过程中展示证书、瑕疵、细节图、售后承诺等信息。
	// 这是 V1 体现“非标品信任建立”的核心玩法。
	RevealTrustCard(ctx context.Context, req *RevealTrustCardRequest, opts ...http.CallOption) (rsp *RevealTrustCardReply, err error)
	// SettleLot 落锤成交。
	//
	// 调用方：主播端/运营端，后续也可以由定时任务自动触发。
	// 状态流转：LIVE -> SETTLED。
	// 服务端动作：锁定 winner、final_price、settled_at，并广播 LOT_SETTLED。
	SettleLot(ctx context.Context, req *SettleLotRequest, opts ...http.CallOption) (rsp *SettleLotReply, err error)
	// StartDuel 进入双人巅峰竞拍模式。
	//
	// 调用方：主播端/运营端，后续也可以由规则引擎自动触发。
	// 用途：最后阶段强化 Top2 竞价展示，制造直播间竞技感。
	// V1 注意：Duel Mode 只是展示强化，不禁止其他观众继续合法出价。
	StartDuel(ctx context.Context, req *StartDuelRequest, opts ...http.CallOption) (rsp *StartDuelReply, err error)
	// StartLot 开拍。
	//
	// 调用方：主播端/运营端。
	// 状态流转：DRAFT -> LIVE。
	// 服务端动作：设置 started_at、ends_at、current_price，并广播 LOT_STARTED。
	StartLot(ctx context.Context, req *StartLotRequest, opts ...http.CallOption) (rsp *StartLotReply, err error)
}

type AuctionServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewAuctionServiceHTTPClient(client *http.Client) AuctionServiceHTTPClient {
	return &AuctionServiceHTTPClientImpl{client}
}

// CancelLot 主播异常取消拍品。
//
// 调用方：主播端/运营端。
// 状态流转：LIVE -> CANCELLED。
// 服务端动作：记录取消原因，并广播 LOT_CANCELLED。
func (c *AuctionServiceHTTPClientImpl) CancelLot(ctx context.Context, in *CancelLotRequest, opts ...http.CallOption) (*CancelLotReply, error) {
	var out CancelLotReply
	pattern := "/api/lots/{lot_id}/cancel"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAuctionServiceCancelLot))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ConsultBuyer 买家找拍品助手。
//
// 调用方：观众端。
// 用途：根据用户输入的品类、预算或用途，返回公开可见的候选竞拍拍品。
// 注意：这里只做找拍品和来源解释，不返回出价建议。
func (c *AuctionServiceHTTPClientImpl) ConsultBuyer(ctx context.Context, in *BuyerConsultRequest, opts ...http.CallOption) (*BuyerConsultReply, error) {
	var out BuyerConsultReply
	pattern := "/api/ai/buyer/consult"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAuctionServiceConsultBuyer))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateLot 创建拍品草稿。
//
// 调用方：主播端/运营端。
// 输入：直播间 ID、商品基础信息、竞拍规则、信任揭示卡片。
// 输出：状态为 DRAFT 的拍品。
// 注意：创建后还没有开拍，观众不能出价。
func (c *AuctionServiceHTTPClientImpl) CreateLot(ctx context.Context, in *CreateLotRequest, opts ...http.CallOption) (*CreateLotReply, error) {
	var out CreateLotReply
	pattern := "/api/lots"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAuctionServiceCreateLot))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateLotDraft 创建空草稿。用于添加拍品页初始化自动保存容器，允许商品资料和竞拍规则为空。
func (c *AuctionServiceHTTPClientImpl) CreateLotDraft(ctx context.Context, in *CreateLotRequest, opts ...http.CallOption) (*CreateLotReply, error) {
	var out CreateLotReply
	pattern := "/api/lots/drafts"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAuctionServiceCreateLotDraft))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetLot 查询拍品详情。
//
// 调用方：主播端、观众端、调试工具。
// 用途：查询某个拍品当前完整状态，包括当前价、领先者、玩法状态等。
func (c *AuctionServiceHTTPClientImpl) GetLot(ctx context.Context, in *GetLotRequest, opts ...http.CallOption) (*GetLotReply, error) {
	var out GetLotReply
	pattern := "/api/lots/{lot_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAuctionServiceGetLot))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetLotResultView 查询拍品结果。
func (c *AuctionServiceHTTPClientImpl) GetLotResultView(ctx context.Context, in *GetLotResultRequest, opts ...http.CallOption) (*GetLotResultReply, error) {
	var out GetLotResultReply
	pattern := "/api/lots/{lot_id}/result"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAuctionServiceGetLotResultView))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetRoomPersonalState 获取当前买家在房间当前版本上的私有覆盖状态。
//
// 调用方：已登录观众端。
// 用途：私人 WebSocket 增量丢失、订单仍在投影时，只恢复当前用户状态。
func (c *AuctionServiceHTTPClientImpl) GetRoomPersonalState(ctx context.Context, in *GetRoomPersonalStateRequest, opts ...http.CallOption) (*GetRoomPersonalStateReply, error) {
	var out GetRoomPersonalStateReply
	pattern := "/api/rooms/{room_id}/me"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAuctionServiceGetRoomPersonalState))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetRoomPresence 获取直播间在线状态。
//
// 调用方：主播端/运营端。
// 用途：工作台展示当前房间 WebSocket 真实连接情况。
func (c *AuctionServiceHTTPClientImpl) GetRoomPresence(ctx context.Context, in *GetRoomPresenceRequest, opts ...http.CallOption) (*GetRoomPresenceReply, error) {
	var out GetRoomPresenceReply
	pattern := "/api/rooms/{room_id}/presence"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAuctionServiceGetRoomPresence))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetRoomSnapshot 获取直播间权威快照。
//
// 调用方：观众端。
// 用途：首次进入直播间、WebSocket 重连、前端状态不可信时，用它恢复当前状态。
func (c *AuctionServiceHTTPClientImpl) GetRoomSnapshot(ctx context.Context, in *GetRoomSnapshotRequest, opts ...http.CallOption) (*GetRoomSnapshotReply, error) {
	var out GetRoomSnapshotReply
	pattern := "/api/rooms/{room_id}/snapshot"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAuctionServiceGetRoomSnapshot))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAdminAuctionOrders 查询后台竞拍订单。
func (c *AuctionServiceHTTPClientImpl) ListAdminAuctionOrders(ctx context.Context, in *ListAuctionOrdersRequest, opts ...http.CallOption) (*ListAuctionOrdersReply, error) {
	var out ListAuctionOrdersReply
	pattern := "/api/admin/orders"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAuctionServiceListAdminAuctionOrders))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAdminLotPage 查询后台拍品。
func (c *AuctionServiceHTTPClientImpl) ListAdminLotPage(ctx context.Context, in *ListAdminLotPageRequest, opts ...http.CallOption) (*ListAdminLotPageReply, error) {
	var out ListAdminLotPageReply
	pattern := "/api/admin/lots"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAuctionServiceListAdminLotPage))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAdminRoomList 查询后台房间。
func (c *AuctionServiceHTTPClientImpl) ListAdminRoomList(ctx context.Context, in *ListAdminRoomsRequest, opts ...http.CallOption) (*ListRoomsReply, error) {
	var out ListRoomsReply
	pattern := "/api/admin/rooms"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAuctionServiceListAdminRoomList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListBuyerSuggestions 获取买家推荐搜索词。
func (c *AuctionServiceHTTPClientImpl) ListBuyerSuggestions(ctx context.Context, in *ListBuyerSuggestionsRequest, opts ...http.CallOption) (*ListBuyerSuggestionsReply, error) {
	var out ListBuyerSuggestionsReply
	pattern := "/api/ai/buyer/suggestions"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAuctionServiceListBuyerSuggestions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListLots 查询直播间拍品列表。
//
// 调用方：主播端/运营端。
// 用途：查看某个直播间下的草稿、竞拍中、已成交拍品。
// V1 可以先只返回少量数据，分页字段为后续预留。
func (c *AuctionServiceHTTPClientImpl) ListLots(ctx context.Context, in *ListLotsRequest, opts ...http.CallOption) (*ListLotsReply, error) {
	var out ListLotsReply
	pattern := "/api/lots"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAuctionServiceListLots))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListMyAuctionOrders 查询当前买家的竞拍订单。
func (c *AuctionServiceHTTPClientImpl) ListMyAuctionOrders(ctx context.Context, in *ListAuctionOrdersRequest, opts ...http.CallOption) (*ListAuctionOrdersReply, error) {
	var out ListAuctionOrdersReply
	pattern := "/api/me/orders"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAuctionServiceListMyAuctionOrders))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListMyBidRecords 查询当前买家的出价记录。
func (c *AuctionServiceHTTPClientImpl) ListMyBidRecords(ctx context.Context, in *ListBidRecordsRequest, opts ...http.CallOption) (*ListBidRecordsReply, error) {
	var out ListBidRecordsReply
	pattern := "/api/me/bids"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAuctionServiceListMyBidRecords))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListPublicRoomList 查询公开房间。
func (c *AuctionServiceHTTPClientImpl) ListPublicRoomList(ctx context.Context, in *ListPublicRoomsRequest, opts ...http.CallOption) (*ListPublicRoomsReply, error) {
	var out ListPublicRoomsReply
	pattern := "/api/rooms"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAuctionServiceListPublicRoomList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListRoomEvents 查询直播间最近事件。
//
// 调用方：主播端/运营端。
// 用途：工作台恢复最近出价、开拍、成交、取消、支付等操作日志。
func (c *AuctionServiceHTTPClientImpl) ListRoomEvents(ctx context.Context, in *ListRoomEventsRequest, opts ...http.CallOption) (*ListRoomEventsReply, error) {
	var out ListRoomEventsReply
	pattern := "/api/rooms/{room_id}/events"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAuctionServiceListRoomEvents))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// PatchLotDraft 静默保存草稿。用于添加拍品页自动保存，允许部分字段更新。
func (c *AuctionServiceHTTPClientImpl) PatchLotDraft(ctx context.Context, in *PatchLotDraftRequest, opts ...http.CallOption) (*PatchLotDraftReply, error) {
	var out PatchLotDraftReply
	pattern := "/api/lots/{lot_id}/draft"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAuctionServicePatchLotDraft))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// PlaceBid 出价。
//
// 调用方：观众端。
// 服务端需要校验：
// - 拍品是否存在；
// - 拍品是否处于 LIVE；
// - 是否已经超时；
// - 出价是否大于等于 current_price + min_increment；
// - 幂等键是否重复。
// 成功后广播 BID_ACCEPTED、LOT_UPDATED、RANKING_UPDATED。
func (c *AuctionServiceHTTPClientImpl) PlaceBid(ctx context.Context, in *PlaceBidRequest, opts ...http.CallOption) (*PlaceBidReply, error) {
	var out PlaceBidReply
	pattern := "/api/lots/{lot_id}/bid"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAuctionServicePlaceBid))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// QueueLot 加入本场队列。用于添加拍品页唯一主动作，成功后仍不直接开拍。
func (c *AuctionServiceHTTPClientImpl) QueueLot(ctx context.Context, in *QueueLotRequest, opts ...http.CallOption) (*QueueLotReply, error) {
	var out QueueLotReply
	pattern := "/api/lots/{lot_id}/queue"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAuctionServiceQueueLot))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RevealTrustCard 主播揭示信任卡片。
//
// 调用方：主播端/运营端。
// 用途：在竞拍过程中展示证书、瑕疵、细节图、售后承诺等信息。
// 这是 V1 体现“非标品信任建立”的核心玩法。
func (c *AuctionServiceHTTPClientImpl) RevealTrustCard(ctx context.Context, in *RevealTrustCardRequest, opts ...http.CallOption) (*RevealTrustCardReply, error) {
	var out RevealTrustCardReply
	pattern := "/api/lots/{lot_id}/trust-cards/{card_id}/reveal"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAuctionServiceRevealTrustCard))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SettleLot 落锤成交。
//
// 调用方：主播端/运营端，后续也可以由定时任务自动触发。
// 状态流转：LIVE -> SETTLED。
// 服务端动作：锁定 winner、final_price、settled_at，并广播 LOT_SETTLED。
func (c *AuctionServiceHTTPClientImpl) SettleLot(ctx context.Context, in *SettleLotRequest, opts ...http.CallOption) (*SettleLotReply, error) {
	var out SettleLotReply
	pattern := "/api/lots/{lot_id}/settle"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAuctionServiceSettleLot))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// StartDuel 进入双人巅峰竞拍模式。
//
// 调用方：主播端/运营端，后续也可以由规则引擎自动触发。
// 用途：最后阶段强化 Top2 竞价展示，制造直播间竞技感。
// V1 注意：Duel Mode 只是展示强化，不禁止其他观众继续合法出价。
func (c *AuctionServiceHTTPClientImpl) StartDuel(ctx context.Context, in *StartDuelRequest, opts ...http.CallOption) (*StartDuelReply, error) {
	var out StartDuelReply
	pattern := "/api/lots/{lot_id}/duel"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAuctionServiceStartDuel))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// StartLot 开拍。
//
// 调用方：主播端/运营端。
// 状态流转：DRAFT -> LIVE。
// 服务端动作：设置 started_at、ends_at、current_price，并广播 LOT_STARTED。
func (c *AuctionServiceHTTPClientImpl) StartLot(ctx context.Context, in *StartLotRequest, opts ...http.CallOption) (*StartLotReply, error) {
	var out StartLotReply
	pattern := "/api/lots/{lot_id}/start"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAuctionServiceStartLot))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
