// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v4.25.8
// source: auction/service/v1/auction.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	AuctionService_CreateLot_FullMethodName              = "/auction.service.v1.AuctionService/CreateLot"
	AuctionService_CreateLotDraft_FullMethodName         = "/auction.service.v1.AuctionService/CreateLotDraft"
	AuctionService_PatchLotDraft_FullMethodName          = "/auction.service.v1.AuctionService/PatchLotDraft"
	AuctionService_QueueLot_FullMethodName               = "/auction.service.v1.AuctionService/QueueLot"
	AuctionService_GetLot_FullMethodName                 = "/auction.service.v1.AuctionService/GetLot"
	AuctionService_ListLots_FullMethodName               = "/auction.service.v1.AuctionService/ListLots"
	AuctionService_StartLot_FullMethodName               = "/auction.service.v1.AuctionService/StartLot"
	AuctionService_PlaceBid_FullMethodName               = "/auction.service.v1.AuctionService/PlaceBid"
	AuctionService_RevealTrustCard_FullMethodName        = "/auction.service.v1.AuctionService/RevealTrustCard"
	AuctionService_StartDuel_FullMethodName              = "/auction.service.v1.AuctionService/StartDuel"
	AuctionService_SettleLot_FullMethodName              = "/auction.service.v1.AuctionService/SettleLot"
	AuctionService_CancelLot_FullMethodName              = "/auction.service.v1.AuctionService/CancelLot"
	AuctionService_GetRoomSnapshot_FullMethodName        = "/auction.service.v1.AuctionService/GetRoomSnapshot"
	AuctionService_GetRoomPresence_FullMethodName        = "/auction.service.v1.AuctionService/GetRoomPresence"
	AuctionService_ListRoomEvents_FullMethodName         = "/auction.service.v1.AuctionService/ListRoomEvents"
	AuctionService_GetLotResultView_FullMethodName       = "/auction.service.v1.AuctionService/GetLotResultView"
	AuctionService_ListMyAuctionOrders_FullMethodName    = "/auction.service.v1.AuctionService/ListMyAuctionOrders"
	AuctionService_ListMyBidRecords_FullMethodName       = "/auction.service.v1.AuctionService/ListMyBidRecords"
	AuctionService_ListAdminAuctionOrders_FullMethodName = "/auction.service.v1.AuctionService/ListAdminAuctionOrders"
	AuctionService_ListAdminLotPage_FullMethodName       = "/auction.service.v1.AuctionService/ListAdminLotPage"
	AuctionService_ListAdminRoomList_FullMethodName      = "/auction.service.v1.AuctionService/ListAdminRoomList"
	AuctionService_ListPublicRoomList_FullMethodName     = "/auction.service.v1.AuctionService/ListPublicRoomList"
	AuctionService_ListBuyerSuggestions_FullMethodName   = "/auction.service.v1.AuctionService/ListBuyerSuggestions"
	AuctionService_ConsultBuyer_FullMethodName           = "/auction.service.v1.AuctionService/ConsultBuyer"
	AuctionService_GetRoomPersonalState_FullMethodName   = "/auction.service.v1.AuctionService/GetRoomPersonalState"
)

// AuctionServiceClient is the client API for AuctionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AuctionService 是 V1 直播竞拍核心服务。
//
// V1 只解决“一个直播间内，一个拍品从创建到落锤”的最小闭环：
// - 主播/运营创建拍品和竞拍规则；
// - 主播开拍；
// - 观众进入直播间，获取当前快照；
// - 观众实时出价；
// - 系统更新当前价、领先者、排行榜；
// - 主播触发信任揭示卡片；
// - 最后阶段可进入 Duel Mode；
// - 主播或系统落锤成交。
//
// 设计边界：
// - V1 暂不处理支付、订单履约、保证金；
// - V1 暂不接真实 AI 模型，玩法阶段先由规则或人工触发；
// - V1 可以先使用单进程内存存储，后续再替换 Redis/MySQL；
// - 该 proto 是前后端契约源头，后续可生成 OpenAPI 和 TypeScript 类型。
//
// 实时通信说明：
// - HTTP/RPC 用于主动操作，例如创建拍品、出价、落锤；
// - WebSocket 用于直播间广播，事件结构统一使用 AuctionEvent；
// - 观众重连后可调用 GetRoomSnapshot 获取权威快照。
type AuctionServiceClient interface {
	// 创建拍品草稿。
	//
	// 调用方：主播端/运营端。
	// 输入：直播间 ID、商品基础信息、竞拍规则、信任揭示卡片。
	// 输出：状态为 DRAFT 的拍品。
	// 注意：创建后还没有开拍，观众不能出价。
	CreateLot(ctx context.Context, in *CreateLotRequest, opts ...grpc.CallOption) (*CreateLotReply, error)
	// 创建空草稿。用于添加拍品页初始化自动保存容器，允许商品资料和竞拍规则为空。
	CreateLotDraft(ctx context.Context, in *CreateLotRequest, opts ...grpc.CallOption) (*CreateLotReply, error)
	// 静默保存草稿。用于添加拍品页自动保存，允许部分字段更新。
	PatchLotDraft(ctx context.Context, in *PatchLotDraftRequest, opts ...grpc.CallOption) (*PatchLotDraftReply, error)
	// 加入本场队列。用于添加拍品页唯一主动作，成功后仍不直接开拍。
	QueueLot(ctx context.Context, in *QueueLotRequest, opts ...grpc.CallOption) (*QueueLotReply, error)
	// 查询拍品详情。
	//
	// 调用方：主播端、观众端、调试工具。
	// 用途：查询某个拍品当前完整状态，包括当前价、领先者、玩法状态等。
	GetLot(ctx context.Context, in *GetLotRequest, opts ...grpc.CallOption) (*GetLotReply, error)
	// 查询直播间拍品列表。
	//
	// 调用方：主播端/运营端。
	// 用途：查看某个直播间下的草稿、竞拍中、已成交拍品。
	// V1 可以先只返回少量数据，分页字段为后续预留。
	ListLots(ctx context.Context, in *ListLotsRequest, opts ...grpc.CallOption) (*ListLotsReply, error)
	// 开拍。
	//
	// 调用方：主播端/运营端。
	// 状态流转：DRAFT -> LIVE。
	// 服务端动作：设置 started_at、ends_at、current_price，并广播 LOT_STARTED。
	StartLot(ctx context.Context, in *StartLotRequest, opts ...grpc.CallOption) (*StartLotReply, error)
	// 出价。
	//
	// 调用方：观众端。
	// 服务端需要校验：
	// - 拍品是否存在；
	// - 拍品是否处于 LIVE；
	// - 是否已经超时；
	// - 出价是否大于等于 current_price + min_increment；
	// - 幂等键是否重复。
	// 成功后广播 BID_ACCEPTED、LOT_UPDATED、RANKING_UPDATED。
	PlaceBid(ctx context.Context, in *PlaceBidRequest, opts ...grpc.CallOption) (*PlaceBidReply, error)
	// 主播揭示信任卡片。
	//
	// 调用方：主播端/运营端。
	// 用途：在竞拍过程中展示证书、瑕疵、细节图、售后承诺等信息。
	// 这是 V1 体现“非标品信任建立”的核心玩法。
	RevealTrustCard(ctx context.Context, in *RevealTrustCardRequest, opts ...grpc.CallOption) (*RevealTrustCardReply, error)
	// 进入双人巅峰竞拍模式。
	//
	// 调用方：主播端/运营端，后续也可以由规则引擎自动触发。
	// 用途：最后阶段强化 Top2 竞价展示，制造直播间竞技感。
	// V1 注意：Duel Mode 只是展示强化，不禁止其他观众继续合法出价。
	StartDuel(ctx context.Context, in *StartDuelRequest, opts ...grpc.CallOption) (*StartDuelReply, error)
	// 落锤成交。
	//
	// 调用方：主播端/运营端，后续也可以由定时任务自动触发。
	// 状态流转：LIVE -> SETTLED。
	// 服务端动作：锁定 winner、final_price、settled_at，并广播 LOT_SETTLED。
	SettleLot(ctx context.Context, in *SettleLotRequest, opts ...grpc.CallOption) (*SettleLotReply, error)
	// 主播异常取消拍品。
	//
	// 调用方：主播端/运营端。
	// 状态流转：LIVE -> CANCELLED。
	// 服务端动作：记录取消原因，并广播 LOT_CANCELLED。
	CancelLot(ctx context.Context, in *CancelLotRequest, opts ...grpc.CallOption) (*CancelLotReply, error)
	// 获取直播间权威快照。
	//
	// 调用方：观众端。
	// 用途：首次进入直播间、WebSocket 重连、前端状态不可信时，用它恢复当前状态。
	GetRoomSnapshot(ctx context.Context, in *GetRoomSnapshotRequest, opts ...grpc.CallOption) (*GetRoomSnapshotReply, error)
	// 获取直播间在线状态。
	//
	// 调用方：主播端/运营端。
	// 用途：工作台展示当前房间 WebSocket 真实连接情况。
	GetRoomPresence(ctx context.Context, in *GetRoomPresenceRequest, opts ...grpc.CallOption) (*GetRoomPresenceReply, error)
	// 查询直播间最近事件。
	//
	// 调用方：主播端/运营端。
	// 用途：工作台恢复最近出价、开拍、成交、取消、支付等操作日志。
	ListRoomEvents(ctx context.Context, in *ListRoomEventsRequest, opts ...grpc.CallOption) (*ListRoomEventsReply, error)
	// 查询拍品结果。
	GetLotResultView(ctx context.Context, in *GetLotResultRequest, opts ...grpc.CallOption) (*GetLotResultReply, error)
	// 查询当前买家的竞拍订单。
	ListMyAuctionOrders(ctx context.Context, in *ListAuctionOrdersRequest, opts ...grpc.CallOption) (*ListAuctionOrdersReply, error)
	// 查询当前买家的出价记录。
	ListMyBidRecords(ctx context.Context, in *ListBidRecordsRequest, opts ...grpc.CallOption) (*ListBidRecordsReply, error)
	// 查询后台竞拍订单。
	ListAdminAuctionOrders(ctx context.Context, in *ListAuctionOrdersRequest, opts ...grpc.CallOption) (*ListAuctionOrdersReply, error)
	// 查询后台拍品。
	ListAdminLotPage(ctx context.Context, in *ListAdminLotPageRequest, opts ...grpc.CallOption) (*ListAdminLotPageReply, error)
	// 查询后台房间。
	ListAdminRoomList(ctx context.Context, in *ListAdminRoomsRequest, opts ...grpc.CallOption) (*ListRoomsReply, error)
	// 查询公开房间。
	ListPublicRoomList(ctx context.Context, in *ListPublicRoomsRequest, opts ...grpc.CallOption) (*ListPublicRoomsReply, error)
	// 获取买家推荐搜索词。
	ListBuyerSuggestions(ctx context.Context, in *ListBuyerSuggestionsRequest, opts ...grpc.CallOption) (*ListBuyerSuggestionsReply, error)
	// 买家找拍品助手。
	//
	// 调用方：观众端。
	// 用途：根据用户输入的品类、预算或用途，返回公开可见的候选竞拍拍品。
	// 注意：这里只做找拍品和来源解释，不返回出价建议。
	ConsultBuyer(ctx context.Context, in *BuyerConsultRequest, opts ...grpc.CallOption) (*BuyerConsultReply, error)
	// 获取当前买家在房间当前版本上的私有覆盖状态。
	//
	// 调用方：已登录观众端。
	// 用途：私人 WebSocket 增量丢失、订单仍在投影时，只恢复当前用户状态。
	GetRoomPersonalState(ctx context.Context, in *GetRoomPersonalStateRequest, opts ...grpc.CallOption) (*GetRoomPersonalStateReply, error)
}

type auctionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuctionServiceClient(cc grpc.ClientConnInterface) AuctionServiceClient {
	return &auctionServiceClient{cc}
}

func (c *auctionServiceClient) CreateLot(ctx context.Context, in *CreateLotRequest, opts ...grpc.CallOption) (*CreateLotReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLotReply)
	err := c.cc.Invoke(ctx, AuctionService_CreateLot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionServiceClient) CreateLotDraft(ctx context.Context, in *CreateLotRequest, opts ...grpc.CallOption) (*CreateLotReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLotReply)
	err := c.cc.Invoke(ctx, AuctionService_CreateLotDraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionServiceClient) PatchLotDraft(ctx context.Context, in *PatchLotDraftRequest, opts ...grpc.CallOption) (*PatchLotDraftReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PatchLotDraftReply)
	err := c.cc.Invoke(ctx, AuctionService_PatchLotDraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionServiceClient) QueueLot(ctx context.Context, in *QueueLotRequest, opts ...grpc.CallOption) (*QueueLotReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueueLotReply)
	err := c.cc.Invoke(ctx, AuctionService_QueueLot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionServiceClient) GetLot(ctx context.Context, in *GetLotRequest, opts ...grpc.CallOption) (*GetLotReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLotReply)
	err := c.cc.Invoke(ctx, AuctionService_GetLot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionServiceClient) ListLots(ctx context.Context, in *ListLotsRequest, opts ...grpc.CallOption) (*ListLotsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLotsReply)
	err := c.cc.Invoke(ctx, AuctionService_ListLots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionServiceClient) StartLot(ctx context.Context, in *StartLotRequest, opts ...grpc.CallOption) (*StartLotReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartLotReply)
	err := c.cc.Invoke(ctx, AuctionService_StartLot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionServiceClient) PlaceBid(ctx context.Context, in *PlaceBidRequest, opts ...grpc.CallOption) (*PlaceBidReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlaceBidReply)
	err := c.cc.Invoke(ctx, AuctionService_PlaceBid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionServiceClient) RevealTrustCard(ctx context.Context, in *RevealTrustCardRequest, opts ...grpc.CallOption) (*RevealTrustCardReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevealTrustCardReply)
	err := c.cc.Invoke(ctx, AuctionService_RevealTrustCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionServiceClient) StartDuel(ctx context.Context, in *StartDuelRequest, opts ...grpc.CallOption) (*StartDuelReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartDuelReply)
	err := c.cc.Invoke(ctx, AuctionService_StartDuel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionServiceClient) SettleLot(ctx context.Context, in *SettleLotRequest, opts ...grpc.CallOption) (*SettleLotReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettleLotReply)
	err := c.cc.Invoke(ctx, AuctionService_SettleLot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionServiceClient) CancelLot(ctx context.Context, in *CancelLotRequest, opts ...grpc.CallOption) (*CancelLotReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelLotReply)
	err := c.cc.Invoke(ctx, AuctionService_CancelLot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionServiceClient) GetRoomSnapshot(ctx context.Context, in *GetRoomSnapshotRequest, opts ...grpc.CallOption) (*GetRoomSnapshotReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoomSnapshotReply)
	err := c.cc.Invoke(ctx, AuctionService_GetRoomSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionServiceClient) GetRoomPresence(ctx context.Context, in *GetRoomPresenceRequest, opts ...grpc.CallOption) (*GetRoomPresenceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoomPresenceReply)
	err := c.cc.Invoke(ctx, AuctionService_GetRoomPresence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionServiceClient) ListRoomEvents(ctx context.Context, in *ListRoomEventsRequest, opts ...grpc.CallOption) (*ListRoomEventsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRoomEventsReply)
	err := c.cc.Invoke(ctx, AuctionService_ListRoomEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionServiceClient) GetLotResultView(ctx context.Context, in *GetLotResultRequest, opts ...grpc.CallOption) (*GetLotResultReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLotResultReply)
	err := c.cc.Invoke(ctx, AuctionService_GetLotResultView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionServiceClient) ListMyAuctionOrders(ctx context.Context, in *ListAuctionOrdersRequest, opts ...grpc.CallOption) (*ListAuctionOrdersReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAuctionOrdersReply)
	err := c.cc.Invoke(ctx, AuctionService_ListMyAuctionOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionServiceClient) ListMyBidRecords(ctx context.Context, in *ListBidRecordsRequest, opts ...grpc.CallOption) (*ListBidRecordsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBidRecordsReply)
	err := c.cc.Invoke(ctx, AuctionService_ListMyBidRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionServiceClient) ListAdminAuctionOrders(ctx context.Context, in *ListAuctionOrdersRequest, opts ...grpc.CallOption) (*ListAuctionOrdersReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAuctionOrdersReply)
	err := c.cc.Invoke(ctx, AuctionService_ListAdminAuctionOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionServiceClient) ListAdminLotPage(ctx context.Context, in *ListAdminLotPageRequest, opts ...grpc.CallOption) (*ListAdminLotPageReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdminLotPageReply)
	err := c.cc.Invoke(ctx, AuctionService_ListAdminLotPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionServiceClient) ListAdminRoomList(ctx context.Context, in *ListAdminRoomsRequest, opts ...grpc.CallOption) (*ListRoomsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRoomsReply)
	err := c.cc.Invoke(ctx, AuctionService_ListAdminRoomList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionServiceClient) ListPublicRoomList(ctx context.Context, in *ListPublicRoomsRequest, opts ...grpc.CallOption) (*ListPublicRoomsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPublicRoomsReply)
	err := c.cc.Invoke(ctx, AuctionService_ListPublicRoomList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionServiceClient) ListBuyerSuggestions(ctx context.Context, in *ListBuyerSuggestionsRequest, opts ...grpc.CallOption) (*ListBuyerSuggestionsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBuyerSuggestionsReply)
	err := c.cc.Invoke(ctx, AuctionService_ListBuyerSuggestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionServiceClient) ConsultBuyer(ctx context.Context, in *BuyerConsultRequest, opts ...grpc.CallOption) (*BuyerConsultReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuyerConsultReply)
	err := c.cc.Invoke(ctx, AuctionService_ConsultBuyer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionServiceClient) GetRoomPersonalState(ctx context.Context, in *GetRoomPersonalStateRequest, opts ...grpc.CallOption) (*GetRoomPersonalStateReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoomPersonalStateReply)
	err := c.cc.Invoke(ctx, AuctionService_GetRoomPersonalState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuctionServiceServer is the server API for AuctionService service.
// All implementations must embed UnimplementedAuctionServiceServer
// for forward compatibility
//
// AuctionService 是 V1 直播竞拍核心服务。
//
// V1 只解决“一个直播间内，一个拍品从创建到落锤”的最小闭环：
// - 主播/运营创建拍品和竞拍规则；
// - 主播开拍；
// - 观众进入直播间，获取当前快照；
// - 观众实时出价；
// - 系统更新当前价、领先者、排行榜；
// - 主播触发信任揭示卡片；
// - 最后阶段可进入 Duel Mode；
// - 主播或系统落锤成交。
//
// 设计边界：
// - V1 暂不处理支付、订单履约、保证金；
// - V1 暂不接真实 AI 模型，玩法阶段先由规则或人工触发；
// - V1 可以先使用单进程内存存储，后续再替换 Redis/MySQL；
// - 该 proto 是前后端契约源头，后续可生成 OpenAPI 和 TypeScript 类型。
//
// 实时通信说明：
// - HTTP/RPC 用于主动操作，例如创建拍品、出价、落锤；
// - WebSocket 用于直播间广播，事件结构统一使用 AuctionEvent；
// - 观众重连后可调用 GetRoomSnapshot 获取权威快照。
type AuctionServiceServer interface {
	// 创建拍品草稿。
	//
	// 调用方：主播端/运营端。
	// 输入：直播间 ID、商品基础信息、竞拍规则、信任揭示卡片。
	// 输出：状态为 DRAFT 的拍品。
	// 注意：创建后还没有开拍，观众不能出价。
	CreateLot(context.Context, *CreateLotRequest) (*CreateLotReply, error)
	// 创建空草稿。用于添加拍品页初始化自动保存容器，允许商品资料和竞拍规则为空。
	CreateLotDraft(context.Context, *CreateLotRequest) (*CreateLotReply, error)
	// 静默保存草稿。用于添加拍品页自动保存，允许部分字段更新。
	PatchLotDraft(context.Context, *PatchLotDraftRequest) (*PatchLotDraftReply, error)
	// 加入本场队列。用于添加拍品页唯一主动作，成功后仍不直接开拍。
	QueueLot(context.Context, *QueueLotRequest) (*QueueLotReply, error)
	// 查询拍品详情。
	//
	// 调用方：主播端、观众端、调试工具。
	// 用途：查询某个拍品当前完整状态，包括当前价、领先者、玩法状态等。
	GetLot(context.Context, *GetLotRequest) (*GetLotReply, error)
	// 查询直播间拍品列表。
	//
	// 调用方：主播端/运营端。
	// 用途：查看某个直播间下的草稿、竞拍中、已成交拍品。
	// V1 可以先只返回少量数据，分页字段为后续预留。
	ListLots(context.Context, *ListLotsRequest) (*ListLotsReply, error)
	// 开拍。
	//
	// 调用方：主播端/运营端。
	// 状态流转：DRAFT -> LIVE。
	// 服务端动作：设置 started_at、ends_at、current_price，并广播 LOT_STARTED。
	StartLot(context.Context, *StartLotRequest) (*StartLotReply, error)
	// 出价。
	//
	// 调用方：观众端。
	// 服务端需要校验：
	// - 拍品是否存在；
	// - 拍品是否处于 LIVE；
	// - 是否已经超时；
	// - 出价是否大于等于 current_price + min_increment；
	// - 幂等键是否重复。
	// 成功后广播 BID_ACCEPTED、LOT_UPDATED、RANKING_UPDATED。
	PlaceBid(context.Context, *PlaceBidRequest) (*PlaceBidReply, error)
	// 主播揭示信任卡片。
	//
	// 调用方：主播端/运营端。
	// 用途：在竞拍过程中展示证书、瑕疵、细节图、售后承诺等信息。
	// 这是 V1 体现“非标品信任建立”的核心玩法。
	RevealTrustCard(context.Context, *RevealTrustCardRequest) (*RevealTrustCardReply, error)
	// 进入双人巅峰竞拍模式。
	//
	// 调用方：主播端/运营端，后续也可以由规则引擎自动触发。
	// 用途：最后阶段强化 Top2 竞价展示，制造直播间竞技感。
	// V1 注意：Duel Mode 只是展示强化，不禁止其他观众继续合法出价。
	StartDuel(context.Context, *StartDuelRequest) (*StartDuelReply, error)
	// 落锤成交。
	//
	// 调用方：主播端/运营端，后续也可以由定时任务自动触发。
	// 状态流转：LIVE -> SETTLED。
	// 服务端动作：锁定 winner、final_price、settled_at，并广播 LOT_SETTLED。
	SettleLot(context.Context, *SettleLotRequest) (*SettleLotReply, error)
	// 主播异常取消拍品。
	//
	// 调用方：主播端/运营端。
	// 状态流转：LIVE -> CANCELLED。
	// 服务端动作：记录取消原因，并广播 LOT_CANCELLED。
	CancelLot(context.Context, *CancelLotRequest) (*CancelLotReply, error)
	// 获取直播间权威快照。
	//
	// 调用方：观众端。
	// 用途：首次进入直播间、WebSocket 重连、前端状态不可信时，用它恢复当前状态。
	GetRoomSnapshot(context.Context, *GetRoomSnapshotRequest) (*GetRoomSnapshotReply, error)
	// 获取直播间在线状态。
	//
	// 调用方：主播端/运营端。
	// 用途：工作台展示当前房间 WebSocket 真实连接情况。
	GetRoomPresence(context.Context, *GetRoomPresenceRequest) (*GetRoomPresenceReply, error)
	// 查询直播间最近事件。
	//
	// 调用方：主播端/运营端。
	// 用途：工作台恢复最近出价、开拍、成交、取消、支付等操作日志。
	ListRoomEvents(context.Context, *ListRoomEventsRequest) (*ListRoomEventsReply, error)
	// 查询拍品结果。
	GetLotResultView(context.Context, *GetLotResultRequest) (*GetLotResultReply, error)
	// 查询当前买家的竞拍订单。
	ListMyAuctionOrders(context.Context, *ListAuctionOrdersRequest) (*ListAuctionOrdersReply, error)
	// 查询当前买家的出价记录。
	ListMyBidRecords(context.Context, *ListBidRecordsRequest) (*ListBidRecordsReply, error)
	// 查询后台竞拍订单。
	ListAdminAuctionOrders(context.Context, *ListAuctionOrdersRequest) (*ListAuctionOrdersReply, error)
	// 查询后台拍品。
	ListAdminLotPage(context.Context, *ListAdminLotPageRequest) (*ListAdminLotPageReply, error)
	// 查询后台房间。
	ListAdminRoomList(context.Context, *ListAdminRoomsRequest) (*ListRoomsReply, error)
	// 查询公开房间。
	ListPublicRoomList(context.Context, *ListPublicRoomsRequest) (*ListPublicRoomsReply, error)
	// 获取买家推荐搜索词。
	ListBuyerSuggestions(context.Context, *ListBuyerSuggestionsRequest) (*ListBuyerSuggestionsReply, error)
	// 买家找拍品助手。
	//
	// 调用方：观众端。
	// 用途：根据用户输入的品类、预算或用途，返回公开可见的候选竞拍拍品。
	// 注意：这里只做找拍品和来源解释，不返回出价建议。
	ConsultBuyer(context.Context, *BuyerConsultRequest) (*BuyerConsultReply, error)
	// 获取当前买家在房间当前版本上的私有覆盖状态。
	//
	// 调用方：已登录观众端。
	// 用途：私人 WebSocket 增量丢失、订单仍在投影时，只恢复当前用户状态。
	GetRoomPersonalState(context.Context, *GetRoomPersonalStateRequest) (*GetRoomPersonalStateReply, error)
	mustEmbedUnimplementedAuctionServiceServer()
}

// UnimplementedAuctionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAuctionServiceServer struct {
}

func (UnimplementedAuctionServiceServer) CreateLot(context.Context, *CreateLotRequest) (*CreateLotReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLot not implemented")
}
func (UnimplementedAuctionServiceServer) CreateLotDraft(context.Context, *CreateLotRequest) (*CreateLotReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLotDraft not implemented")
}
func (UnimplementedAuctionServiceServer) PatchLotDraft(context.Context, *PatchLotDraftRequest) (*PatchLotDraftReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatchLotDraft not implemented")
}
func (UnimplementedAuctionServiceServer) QueueLot(context.Context, *QueueLotRequest) (*QueueLotReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueueLot not implemented")
}
func (UnimplementedAuctionServiceServer) GetLot(context.Context, *GetLotRequest) (*GetLotReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLot not implemented")
}
func (UnimplementedAuctionServiceServer) ListLots(context.Context, *ListLotsRequest) (*ListLotsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLots not implemented")
}
func (UnimplementedAuctionServiceServer) StartLot(context.Context, *StartLotRequest) (*StartLotReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartLot not implemented")
}
func (UnimplementedAuctionServiceServer) PlaceBid(context.Context, *PlaceBidRequest) (*PlaceBidReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlaceBid not implemented")
}
func (UnimplementedAuctionServiceServer) RevealTrustCard(context.Context, *RevealTrustCardRequest) (*RevealTrustCardReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevealTrustCard not implemented")
}
func (UnimplementedAuctionServiceServer) StartDuel(context.Context, *StartDuelRequest) (*StartDuelReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartDuel not implemented")
}
func (UnimplementedAuctionServiceServer) SettleLot(context.Context, *SettleLotRequest) (*SettleLotReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SettleLot not implemented")
}
func (UnimplementedAuctionServiceServer) CancelLot(context.Context, *CancelLotRequest) (*CancelLotReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelLot not implemented")
}
func (UnimplementedAuctionServiceServer) GetRoomSnapshot(context.Context, *GetRoomSnapshotRequest) (*GetRoomSnapshotReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoomSnapshot not implemented")
}
func (UnimplementedAuctionServiceServer) GetRoomPresence(context.Context, *GetRoomPresenceRequest) (*GetRoomPresenceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoomPresence not implemented")
}
func (UnimplementedAuctionServiceServer) ListRoomEvents(context.Context, *ListRoomEventsRequest) (*ListRoomEventsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRoomEvents not implemented")
}
func (UnimplementedAuctionServiceServer) GetLotResultView(context.Context, *GetLotResultRequest) (*GetLotResultReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLotResultView not implemented")
}
func (UnimplementedAuctionServiceServer) ListMyAuctionOrders(context.Context, *ListAuctionOrdersRequest) (*ListAuctionOrdersReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMyAuctionOrders not implemented")
}
func (UnimplementedAuctionServiceServer) ListMyBidRecords(context.Context, *ListBidRecordsRequest) (*ListBidRecordsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMyBidRecords not implemented")
}
func (UnimplementedAuctionServiceServer) ListAdminAuctionOrders(context.Context, *ListAuctionOrdersRequest) (*ListAuctionOrdersReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAdminAuctionOrders not implemented")
}
func (UnimplementedAuctionServiceServer) ListAdminLotPage(context.Context, *ListAdminLotPageRequest) (*ListAdminLotPageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAdminLotPage not implemented")
}
func (UnimplementedAuctionServiceServer) ListAdminRoomList(context.Context, *ListAdminRoomsRequest) (*ListRoomsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAdminRoomList not implemented")
}
func (UnimplementedAuctionServiceServer) ListPublicRoomList(context.Context, *ListPublicRoomsRequest) (*ListPublicRoomsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPublicRoomList not implemented")
}
func (UnimplementedAuctionServiceServer) ListBuyerSuggestions(context.Context, *ListBuyerSuggestionsRequest) (*ListBuyerSuggestionsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBuyerSuggestions not implemented")
}
func (UnimplementedAuctionServiceServer) ConsultBuyer(context.Context, *BuyerConsultRequest) (*BuyerConsultReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConsultBuyer not implemented")
}
func (UnimplementedAuctionServiceServer) GetRoomPersonalState(context.Context, *GetRoomPersonalStateRequest) (*GetRoomPersonalStateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoomPersonalState not implemented")
}
func (UnimplementedAuctionServiceServer) mustEmbedUnimplementedAuctionServiceServer() {}

// UnsafeAuctionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuctionServiceServer will
// result in compilation errors.
type UnsafeAuctionServiceServer interface {
	mustEmbedUnimplementedAuctionServiceServer()
}

func RegisterAuctionServiceServer(s grpc.ServiceRegistrar, srv AuctionServiceServer) {
	s.RegisterService(&AuctionService_ServiceDesc, srv)
}

func _AuctionService_CreateLot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionServiceServer).CreateLot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionService_CreateLot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionServiceServer).CreateLot(ctx, req.(*CreateLotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionService_CreateLotDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionServiceServer).CreateLotDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionService_CreateLotDraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionServiceServer).CreateLotDraft(ctx, req.(*CreateLotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionService_PatchLotDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchLotDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionServiceServer).PatchLotDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionService_PatchLotDraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionServiceServer).PatchLotDraft(ctx, req.(*PatchLotDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionService_QueueLot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueueLotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionServiceServer).QueueLot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionService_QueueLot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionServiceServer).QueueLot(ctx, req.(*QueueLotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionService_GetLot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionServiceServer).GetLot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionService_GetLot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionServiceServer).GetLot(ctx, req.(*GetLotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionService_ListLots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionServiceServer).ListLots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionService_ListLots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionServiceServer).ListLots(ctx, req.(*ListLotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionService_StartLot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartLotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionServiceServer).StartLot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionService_StartLot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionServiceServer).StartLot(ctx, req.(*StartLotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionService_PlaceBid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceBidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionServiceServer).PlaceBid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionService_PlaceBid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionServiceServer).PlaceBid(ctx, req.(*PlaceBidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionService_RevealTrustCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevealTrustCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionServiceServer).RevealTrustCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionService_RevealTrustCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionServiceServer).RevealTrustCard(ctx, req.(*RevealTrustCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionService_StartDuel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartDuelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionServiceServer).StartDuel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionService_StartDuel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionServiceServer).StartDuel(ctx, req.(*StartDuelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionService_SettleLot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleLotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionServiceServer).SettleLot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionService_SettleLot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionServiceServer).SettleLot(ctx, req.(*SettleLotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionService_CancelLot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelLotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionServiceServer).CancelLot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionService_CancelLot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionServiceServer).CancelLot(ctx, req.(*CancelLotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionService_GetRoomSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoomSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionServiceServer).GetRoomSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionService_GetRoomSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionServiceServer).GetRoomSnapshot(ctx, req.(*GetRoomSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionService_GetRoomPresence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoomPresenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionServiceServer).GetRoomPresence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionService_GetRoomPresence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionServiceServer).GetRoomPresence(ctx, req.(*GetRoomPresenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionService_ListRoomEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRoomEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionServiceServer).ListRoomEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionService_ListRoomEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionServiceServer).ListRoomEvents(ctx, req.(*ListRoomEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionService_GetLotResultView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLotResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionServiceServer).GetLotResultView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionService_GetLotResultView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionServiceServer).GetLotResultView(ctx, req.(*GetLotResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionService_ListMyAuctionOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAuctionOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionServiceServer).ListMyAuctionOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionService_ListMyAuctionOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionServiceServer).ListMyAuctionOrders(ctx, req.(*ListAuctionOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionService_ListMyBidRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBidRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionServiceServer).ListMyBidRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionService_ListMyBidRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionServiceServer).ListMyBidRecords(ctx, req.(*ListBidRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionService_ListAdminAuctionOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAuctionOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionServiceServer).ListAdminAuctionOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionService_ListAdminAuctionOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionServiceServer).ListAdminAuctionOrders(ctx, req.(*ListAuctionOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionService_ListAdminLotPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdminLotPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionServiceServer).ListAdminLotPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionService_ListAdminLotPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionServiceServer).ListAdminLotPage(ctx, req.(*ListAdminLotPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionService_ListAdminRoomList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdminRoomsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionServiceServer).ListAdminRoomList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionService_ListAdminRoomList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionServiceServer).ListAdminRoomList(ctx, req.(*ListAdminRoomsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionService_ListPublicRoomList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPublicRoomsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionServiceServer).ListPublicRoomList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionService_ListPublicRoomList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionServiceServer).ListPublicRoomList(ctx, req.(*ListPublicRoomsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionService_ListBuyerSuggestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBuyerSuggestionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionServiceServer).ListBuyerSuggestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionService_ListBuyerSuggestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionServiceServer).ListBuyerSuggestions(ctx, req.(*ListBuyerSuggestionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionService_ConsultBuyer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuyerConsultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionServiceServer).ConsultBuyer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionService_ConsultBuyer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionServiceServer).ConsultBuyer(ctx, req.(*BuyerConsultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionService_GetRoomPersonalState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoomPersonalStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionServiceServer).GetRoomPersonalState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionService_GetRoomPersonalState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionServiceServer).GetRoomPersonalState(ctx, req.(*GetRoomPersonalStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuctionService_ServiceDesc is the grpc.ServiceDesc for AuctionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuctionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auction.service.v1.AuctionService",
	HandlerType: (*AuctionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLot",
			Handler:    _AuctionService_CreateLot_Handler,
		},
		{
			MethodName: "CreateLotDraft",
			Handler:    _AuctionService_CreateLotDraft_Handler,
		},
		{
			MethodName: "PatchLotDraft",
			Handler:    _AuctionService_PatchLotDraft_Handler,
		},
		{
			MethodName: "QueueLot",
			Handler:    _AuctionService_QueueLot_Handler,
		},
		{
			MethodName: "GetLot",
			Handler:    _AuctionService_GetLot_Handler,
		},
		{
			MethodName: "ListLots",
			Handler:    _AuctionService_ListLots_Handler,
		},
		{
			MethodName: "StartLot",
			Handler:    _AuctionService_StartLot_Handler,
		},
		{
			MethodName: "PlaceBid",
			Handler:    _AuctionService_PlaceBid_Handler,
		},
		{
			MethodName: "RevealTrustCard",
			Handler:    _AuctionService_RevealTrustCard_Handler,
		},
		{
			MethodName: "StartDuel",
			Handler:    _AuctionService_StartDuel_Handler,
		},
		{
			MethodName: "SettleLot",
			Handler:    _AuctionService_SettleLot_Handler,
		},
		{
			MethodName: "CancelLot",
			Handler:    _AuctionService_CancelLot_Handler,
		},
		{
			MethodName: "GetRoomSnapshot",
			Handler:    _AuctionService_GetRoomSnapshot_Handler,
		},
		{
			MethodName: "GetRoomPresence",
			Handler:    _AuctionService_GetRoomPresence_Handler,
		},
		{
			MethodName: "ListRoomEvents",
			Handler:    _AuctionService_ListRoomEvents_Handler,
		},
		{
			MethodName: "GetLotResultView",
			Handler:    _AuctionService_GetLotResultView_Handler,
		},
		{
			MethodName: "ListMyAuctionOrders",
			Handler:    _AuctionService_ListMyAuctionOrders_Handler,
		},
		{
			MethodName: "ListMyBidRecords",
			Handler:    _AuctionService_ListMyBidRecords_Handler,
		},
		{
			MethodName: "ListAdminAuctionOrders",
			Handler:    _AuctionService_ListAdminAuctionOrders_Handler,
		},
		{
			MethodName: "ListAdminLotPage",
			Handler:    _AuctionService_ListAdminLotPage_Handler,
		},
		{
			MethodName: "ListAdminRoomList",
			Handler:    _AuctionService_ListAdminRoomList_Handler,
		},
		{
			MethodName: "ListPublicRoomList",
			Handler:    _AuctionService_ListPublicRoomList_Handler,
		},
		{
			MethodName: "ListBuyerSuggestions",
			Handler:    _AuctionService_ListBuyerSuggestions_Handler,
		},
		{
			MethodName: "ConsultBuyer",
			Handler:    _AuctionService_ConsultBuyer_Handler,
		},
		{
			MethodName: "GetRoomPersonalState",
			Handler:    _AuctionService_GetRoomPersonalState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auction/service/v1/auction.proto",
}

const (
	AuctionCommandService_StartLot_FullMethodName        = "/auction.service.v1.AuctionCommandService/StartLot"
	AuctionCommandService_PlaceBid_FullMethodName        = "/auction.service.v1.AuctionCommandService/PlaceBid"
	AuctionCommandService_RevealTrustCard_FullMethodName = "/auction.service.v1.AuctionCommandService/RevealTrustCard"
	AuctionCommandService_StartDuel_FullMethodName       = "/auction.service.v1.AuctionCommandService/StartDuel"
	AuctionCommandService_SettleLot_FullMethodName       = "/auction.service.v1.AuctionCommandService/SettleLot"
	AuctionCommandService_CancelLot_FullMethodName       = "/auction.service.v1.AuctionCommandService/CancelLot"
)

// AuctionCommandServiceClient is the client API for AuctionCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AuctionCommandService 是 gateway 到 auction-service 的内部同步边界。
//
// 只有会改变竞拍运行态的核心命令进入该服务。反狙击延时属于 PlaceBid
// 的同一次 Redis Lua 原子裁决，不暴露独立 RPC，避免检查与延时之间产生竞态。
// 该服务不提供 HTTP 映射，也不应直接暴露到公网。
type AuctionCommandServiceClient interface {
	StartLot(ctx context.Context, in *StartLotRequest, opts ...grpc.CallOption) (*StartLotReply, error)
	PlaceBid(ctx context.Context, in *PlaceBidRequest, opts ...grpc.CallOption) (*PlaceBidReply, error)
	RevealTrustCard(ctx context.Context, in *RevealTrustCardRequest, opts ...grpc.CallOption) (*RevealTrustCardReply, error)
	StartDuel(ctx context.Context, in *StartDuelRequest, opts ...grpc.CallOption) (*StartDuelReply, error)
	SettleLot(ctx context.Context, in *SettleLotRequest, opts ...grpc.CallOption) (*SettleLotReply, error)
	CancelLot(ctx context.Context, in *CancelLotRequest, opts ...grpc.CallOption) (*CancelLotReply, error)
}

type auctionCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuctionCommandServiceClient(cc grpc.ClientConnInterface) AuctionCommandServiceClient {
	return &auctionCommandServiceClient{cc}
}

func (c *auctionCommandServiceClient) StartLot(ctx context.Context, in *StartLotRequest, opts ...grpc.CallOption) (*StartLotReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartLotReply)
	err := c.cc.Invoke(ctx, AuctionCommandService_StartLot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionCommandServiceClient) PlaceBid(ctx context.Context, in *PlaceBidRequest, opts ...grpc.CallOption) (*PlaceBidReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlaceBidReply)
	err := c.cc.Invoke(ctx, AuctionCommandService_PlaceBid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionCommandServiceClient) RevealTrustCard(ctx context.Context, in *RevealTrustCardRequest, opts ...grpc.CallOption) (*RevealTrustCardReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevealTrustCardReply)
	err := c.cc.Invoke(ctx, AuctionCommandService_RevealTrustCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionCommandServiceClient) StartDuel(ctx context.Context, in *StartDuelRequest, opts ...grpc.CallOption) (*StartDuelReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartDuelReply)
	err := c.cc.Invoke(ctx, AuctionCommandService_StartDuel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionCommandServiceClient) SettleLot(ctx context.Context, in *SettleLotRequest, opts ...grpc.CallOption) (*SettleLotReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettleLotReply)
	err := c.cc.Invoke(ctx, AuctionCommandService_SettleLot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionCommandServiceClient) CancelLot(ctx context.Context, in *CancelLotRequest, opts ...grpc.CallOption) (*CancelLotReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelLotReply)
	err := c.cc.Invoke(ctx, AuctionCommandService_CancelLot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuctionCommandServiceServer is the server API for AuctionCommandService service.
// All implementations must embed UnimplementedAuctionCommandServiceServer
// for forward compatibility
//
// AuctionCommandService 是 gateway 到 auction-service 的内部同步边界。
//
// 只有会改变竞拍运行态的核心命令进入该服务。反狙击延时属于 PlaceBid
// 的同一次 Redis Lua 原子裁决，不暴露独立 RPC，避免检查与延时之间产生竞态。
// 该服务不提供 HTTP 映射，也不应直接暴露到公网。
type AuctionCommandServiceServer interface {
	StartLot(context.Context, *StartLotRequest) (*StartLotReply, error)
	PlaceBid(context.Context, *PlaceBidRequest) (*PlaceBidReply, error)
	RevealTrustCard(context.Context, *RevealTrustCardRequest) (*RevealTrustCardReply, error)
	StartDuel(context.Context, *StartDuelRequest) (*StartDuelReply, error)
	SettleLot(context.Context, *SettleLotRequest) (*SettleLotReply, error)
	CancelLot(context.Context, *CancelLotRequest) (*CancelLotReply, error)
	mustEmbedUnimplementedAuctionCommandServiceServer()
}

// UnimplementedAuctionCommandServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAuctionCommandServiceServer struct {
}

func (UnimplementedAuctionCommandServiceServer) StartLot(context.Context, *StartLotRequest) (*StartLotReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartLot not implemented")
}
func (UnimplementedAuctionCommandServiceServer) PlaceBid(context.Context, *PlaceBidRequest) (*PlaceBidReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlaceBid not implemented")
}
func (UnimplementedAuctionCommandServiceServer) RevealTrustCard(context.Context, *RevealTrustCardRequest) (*RevealTrustCardReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevealTrustCard not implemented")
}
func (UnimplementedAuctionCommandServiceServer) StartDuel(context.Context, *StartDuelRequest) (*StartDuelReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartDuel not implemented")
}
func (UnimplementedAuctionCommandServiceServer) SettleLot(context.Context, *SettleLotRequest) (*SettleLotReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SettleLot not implemented")
}
func (UnimplementedAuctionCommandServiceServer) CancelLot(context.Context, *CancelLotRequest) (*CancelLotReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelLot not implemented")
}
func (UnimplementedAuctionCommandServiceServer) mustEmbedUnimplementedAuctionCommandServiceServer() {}

// UnsafeAuctionCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuctionCommandServiceServer will
// result in compilation errors.
type UnsafeAuctionCommandServiceServer interface {
	mustEmbedUnimplementedAuctionCommandServiceServer()
}

func RegisterAuctionCommandServiceServer(s grpc.ServiceRegistrar, srv AuctionCommandServiceServer) {
	s.RegisterService(&AuctionCommandService_ServiceDesc, srv)
}

func _AuctionCommandService_StartLot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartLotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionCommandServiceServer).StartLot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionCommandService_StartLot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionCommandServiceServer).StartLot(ctx, req.(*StartLotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionCommandService_PlaceBid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceBidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionCommandServiceServer).PlaceBid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionCommandService_PlaceBid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionCommandServiceServer).PlaceBid(ctx, req.(*PlaceBidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionCommandService_RevealTrustCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevealTrustCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionCommandServiceServer).RevealTrustCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionCommandService_RevealTrustCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionCommandServiceServer).RevealTrustCard(ctx, req.(*RevealTrustCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionCommandService_StartDuel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartDuelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionCommandServiceServer).StartDuel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionCommandService_StartDuel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionCommandServiceServer).StartDuel(ctx, req.(*StartDuelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionCommandService_SettleLot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleLotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionCommandServiceServer).SettleLot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionCommandService_SettleLot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionCommandServiceServer).SettleLot(ctx, req.(*SettleLotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionCommandService_CancelLot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelLotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionCommandServiceServer).CancelLot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionCommandService_CancelLot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionCommandServiceServer).CancelLot(ctx, req.(*CancelLotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuctionCommandService_ServiceDesc is the grpc.ServiceDesc for AuctionCommandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuctionCommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auction.service.v1.AuctionCommandService",
	HandlerType: (*AuctionCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartLot",
			Handler:    _AuctionCommandService_StartLot_Handler,
		},
		{
			MethodName: "PlaceBid",
			Handler:    _AuctionCommandService_PlaceBid_Handler,
		},
		{
			MethodName: "RevealTrustCard",
			Handler:    _AuctionCommandService_RevealTrustCard_Handler,
		},
		{
			MethodName: "StartDuel",
			Handler:    _AuctionCommandService_StartDuel_Handler,
		},
		{
			MethodName: "SettleLot",
			Handler:    _AuctionCommandService_SettleLot_Handler,
		},
		{
			MethodName: "CancelLot",
			Handler:    _AuctionCommandService_CancelLot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auction/service/v1/auction.proto",
}
