// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v4.25.8
// source: auction/service/v1/shop.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	ShopService_ListProducts_FullMethodName              = "/auction.service.v1.ShopService/ListProducts"
	ShopService_GetProduct_FullMethodName                = "/auction.service.v1.ShopService/GetProduct"
	ShopService_ListDeliveryAddresses_FullMethodName     = "/auction.service.v1.ShopService/ListDeliveryAddresses"
	ShopService_CreateDeliveryAddress_FullMethodName     = "/auction.service.v1.ShopService/CreateDeliveryAddress"
	ShopService_UpdateDeliveryAddress_FullMethodName     = "/auction.service.v1.ShopService/UpdateDeliveryAddress"
	ShopService_DeleteDeliveryAddress_FullMethodName     = "/auction.service.v1.ShopService/DeleteDeliveryAddress"
	ShopService_SetDefaultDeliveryAddress_FullMethodName = "/auction.service.v1.ShopService/SetDefaultDeliveryAddress"
	ShopService_CreateDepositHold_FullMethodName         = "/auction.service.v1.ShopService/CreateDepositHold"
	ShopService_GetMyDepositHold_FullMethodName          = "/auction.service.v1.ShopService/GetMyDepositHold"
	ShopService_CreateShopOrder_FullMethodName           = "/auction.service.v1.ShopService/CreateShopOrder"
	ShopService_ListMyShopOrders_FullMethodName          = "/auction.service.v1.ShopService/ListMyShopOrders"
	ShopService_MockPayShopOrder_FullMethodName          = "/auction.service.v1.ShopService/MockPayShopOrder"
	ShopService_ListMyUnifiedOrders_FullMethodName       = "/auction.service.v1.ShopService/ListMyUnifiedOrders"
	ShopService_ListMyFrequentStores_FullMethodName      = "/auction.service.v1.ShopService/ListMyFrequentStores"
	ShopService_GetMyUnifiedOrder_FullMethodName         = "/auction.service.v1.ShopService/GetMyUnifiedOrder"
	ShopService_MockPayUnifiedOrder_FullMethodName       = "/auction.service.v1.ShopService/MockPayUnifiedOrder"
)

// ShopServiceClient is the client API for ShopService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ShopService covers buyer commerce APIs used by the H5 client.
type ShopServiceClient interface {
	ListProducts(ctx context.Context, in *ListProductsRequest, opts ...grpc.CallOption) (*ListProductsReply, error)
	GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductReply, error)
	ListDeliveryAddresses(ctx context.Context, in *ListDeliveryAddressesRequest, opts ...grpc.CallOption) (*ListDeliveryAddressesReply, error)
	CreateDeliveryAddress(ctx context.Context, in *CreateDeliveryAddressRequest, opts ...grpc.CallOption) (*CreateDeliveryAddressReply, error)
	UpdateDeliveryAddress(ctx context.Context, in *UpdateDeliveryAddressRequest, opts ...grpc.CallOption) (*UpdateDeliveryAddressReply, error)
	DeleteDeliveryAddress(ctx context.Context, in *DeleteDeliveryAddressRequest, opts ...grpc.CallOption) (*DeleteDeliveryAddressReply, error)
	SetDefaultDeliveryAddress(ctx context.Context, in *SetDefaultDeliveryAddressRequest, opts ...grpc.CallOption) (*ListDeliveryAddressesReply, error)
	CreateDepositHold(ctx context.Context, in *CreateDepositHoldRequest, opts ...grpc.CallOption) (*CreateDepositHoldReply, error)
	GetMyDepositHold(ctx context.Context, in *GetMyDepositHoldRequest, opts ...grpc.CallOption) (*GetMyDepositHoldReply, error)
	CreateShopOrder(ctx context.Context, in *CreateShopOrderRequest, opts ...grpc.CallOption) (*CreateShopOrderReply, error)
	ListMyShopOrders(ctx context.Context, in *ListMyShopOrdersRequest, opts ...grpc.CallOption) (*ListMyShopOrdersReply, error)
	MockPayShopOrder(ctx context.Context, in *MockPayShopOrderRequest, opts ...grpc.CallOption) (*MockPayShopOrderReply, error)
	ListMyUnifiedOrders(ctx context.Context, in *ListMyUnifiedOrdersRequest, opts ...grpc.CallOption) (*ListMyUnifiedOrdersReply, error)
	ListMyFrequentStores(ctx context.Context, in *ListMyFrequentStoresRequest, opts ...grpc.CallOption) (*ListMyFrequentStoresReply, error)
	GetMyUnifiedOrder(ctx context.Context, in *GetMyUnifiedOrderRequest, opts ...grpc.CallOption) (*GetMyUnifiedOrderReply, error)
	MockPayUnifiedOrder(ctx context.Context, in *MockPayUnifiedOrderRequest, opts ...grpc.CallOption) (*MockPayUnifiedOrderReply, error)
}

type shopServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShopServiceClient(cc grpc.ClientConnInterface) ShopServiceClient {
	return &shopServiceClient{cc}
}

func (c *shopServiceClient) ListProducts(ctx context.Context, in *ListProductsRequest, opts ...grpc.CallOption) (*ListProductsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProductsReply)
	err := c.cc.Invoke(ctx, ShopService_ListProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductReply)
	err := c.cc.Invoke(ctx, ShopService_GetProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) ListDeliveryAddresses(ctx context.Context, in *ListDeliveryAddressesRequest, opts ...grpc.CallOption) (*ListDeliveryAddressesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDeliveryAddressesReply)
	err := c.cc.Invoke(ctx, ShopService_ListDeliveryAddresses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) CreateDeliveryAddress(ctx context.Context, in *CreateDeliveryAddressRequest, opts ...grpc.CallOption) (*CreateDeliveryAddressReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDeliveryAddressReply)
	err := c.cc.Invoke(ctx, ShopService_CreateDeliveryAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) UpdateDeliveryAddress(ctx context.Context, in *UpdateDeliveryAddressRequest, opts ...grpc.CallOption) (*UpdateDeliveryAddressReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDeliveryAddressReply)
	err := c.cc.Invoke(ctx, ShopService_UpdateDeliveryAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) DeleteDeliveryAddress(ctx context.Context, in *DeleteDeliveryAddressRequest, opts ...grpc.CallOption) (*DeleteDeliveryAddressReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDeliveryAddressReply)
	err := c.cc.Invoke(ctx, ShopService_DeleteDeliveryAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) SetDefaultDeliveryAddress(ctx context.Context, in *SetDefaultDeliveryAddressRequest, opts ...grpc.CallOption) (*ListDeliveryAddressesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDeliveryAddressesReply)
	err := c.cc.Invoke(ctx, ShopService_SetDefaultDeliveryAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) CreateDepositHold(ctx context.Context, in *CreateDepositHoldRequest, opts ...grpc.CallOption) (*CreateDepositHoldReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDepositHoldReply)
	err := c.cc.Invoke(ctx, ShopService_CreateDepositHold_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) GetMyDepositHold(ctx context.Context, in *GetMyDepositHoldRequest, opts ...grpc.CallOption) (*GetMyDepositHoldReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMyDepositHoldReply)
	err := c.cc.Invoke(ctx, ShopService_GetMyDepositHold_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) CreateShopOrder(ctx context.Context, in *CreateShopOrderRequest, opts ...grpc.CallOption) (*CreateShopOrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateShopOrderReply)
	err := c.cc.Invoke(ctx, ShopService_CreateShopOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) ListMyShopOrders(ctx context.Context, in *ListMyShopOrdersRequest, opts ...grpc.CallOption) (*ListMyShopOrdersReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMyShopOrdersReply)
	err := c.cc.Invoke(ctx, ShopService_ListMyShopOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) MockPayShopOrder(ctx context.Context, in *MockPayShopOrderRequest, opts ...grpc.CallOption) (*MockPayShopOrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MockPayShopOrderReply)
	err := c.cc.Invoke(ctx, ShopService_MockPayShopOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) ListMyUnifiedOrders(ctx context.Context, in *ListMyUnifiedOrdersRequest, opts ...grpc.CallOption) (*ListMyUnifiedOrdersReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMyUnifiedOrdersReply)
	err := c.cc.Invoke(ctx, ShopService_ListMyUnifiedOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) ListMyFrequentStores(ctx context.Context, in *ListMyFrequentStoresRequest, opts ...grpc.CallOption) (*ListMyFrequentStoresReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMyFrequentStoresReply)
	err := c.cc.Invoke(ctx, ShopService_ListMyFrequentStores_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) GetMyUnifiedOrder(ctx context.Context, in *GetMyUnifiedOrderRequest, opts ...grpc.CallOption) (*GetMyUnifiedOrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMyUnifiedOrderReply)
	err := c.cc.Invoke(ctx, ShopService_GetMyUnifiedOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopServiceClient) MockPayUnifiedOrder(ctx context.Context, in *MockPayUnifiedOrderRequest, opts ...grpc.CallOption) (*MockPayUnifiedOrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MockPayUnifiedOrderReply)
	err := c.cc.Invoke(ctx, ShopService_MockPayUnifiedOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShopServiceServer is the server API for ShopService service.
// All implementations must embed UnimplementedShopServiceServer
// for forward compatibility
//
// ShopService covers buyer commerce APIs used by the H5 client.
type ShopServiceServer interface {
	ListProducts(context.Context, *ListProductsRequest) (*ListProductsReply, error)
	GetProduct(context.Context, *GetProductRequest) (*GetProductReply, error)
	ListDeliveryAddresses(context.Context, *ListDeliveryAddressesRequest) (*ListDeliveryAddressesReply, error)
	CreateDeliveryAddress(context.Context, *CreateDeliveryAddressRequest) (*CreateDeliveryAddressReply, error)
	UpdateDeliveryAddress(context.Context, *UpdateDeliveryAddressRequest) (*UpdateDeliveryAddressReply, error)
	DeleteDeliveryAddress(context.Context, *DeleteDeliveryAddressRequest) (*DeleteDeliveryAddressReply, error)
	SetDefaultDeliveryAddress(context.Context, *SetDefaultDeliveryAddressRequest) (*ListDeliveryAddressesReply, error)
	CreateDepositHold(context.Context, *CreateDepositHoldRequest) (*CreateDepositHoldReply, error)
	GetMyDepositHold(context.Context, *GetMyDepositHoldRequest) (*GetMyDepositHoldReply, error)
	CreateShopOrder(context.Context, *CreateShopOrderRequest) (*CreateShopOrderReply, error)
	ListMyShopOrders(context.Context, *ListMyShopOrdersRequest) (*ListMyShopOrdersReply, error)
	MockPayShopOrder(context.Context, *MockPayShopOrderRequest) (*MockPayShopOrderReply, error)
	ListMyUnifiedOrders(context.Context, *ListMyUnifiedOrdersRequest) (*ListMyUnifiedOrdersReply, error)
	ListMyFrequentStores(context.Context, *ListMyFrequentStoresRequest) (*ListMyFrequentStoresReply, error)
	GetMyUnifiedOrder(context.Context, *GetMyUnifiedOrderRequest) (*GetMyUnifiedOrderReply, error)
	MockPayUnifiedOrder(context.Context, *MockPayUnifiedOrderRequest) (*MockPayUnifiedOrderReply, error)
	mustEmbedUnimplementedShopServiceServer()
}

// UnimplementedShopServiceServer must be embedded to have forward compatible implementations.
type UnimplementedShopServiceServer struct {
}

func (UnimplementedShopServiceServer) ListProducts(context.Context, *ListProductsRequest) (*ListProductsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProducts not implemented")
}
func (UnimplementedShopServiceServer) GetProduct(context.Context, *GetProductRequest) (*GetProductReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProduct not implemented")
}
func (UnimplementedShopServiceServer) ListDeliveryAddresses(context.Context, *ListDeliveryAddressesRequest) (*ListDeliveryAddressesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDeliveryAddresses not implemented")
}
func (UnimplementedShopServiceServer) CreateDeliveryAddress(context.Context, *CreateDeliveryAddressRequest) (*CreateDeliveryAddressReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDeliveryAddress not implemented")
}
func (UnimplementedShopServiceServer) UpdateDeliveryAddress(context.Context, *UpdateDeliveryAddressRequest) (*UpdateDeliveryAddressReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDeliveryAddress not implemented")
}
func (UnimplementedShopServiceServer) DeleteDeliveryAddress(context.Context, *DeleteDeliveryAddressRequest) (*DeleteDeliveryAddressReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDeliveryAddress not implemented")
}
func (UnimplementedShopServiceServer) SetDefaultDeliveryAddress(context.Context, *SetDefaultDeliveryAddressRequest) (*ListDeliveryAddressesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDefaultDeliveryAddress not implemented")
}
func (UnimplementedShopServiceServer) CreateDepositHold(context.Context, *CreateDepositHoldRequest) (*CreateDepositHoldReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDepositHold not implemented")
}
func (UnimplementedShopServiceServer) GetMyDepositHold(context.Context, *GetMyDepositHoldRequest) (*GetMyDepositHoldReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMyDepositHold not implemented")
}
func (UnimplementedShopServiceServer) CreateShopOrder(context.Context, *CreateShopOrderRequest) (*CreateShopOrderReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateShopOrder not implemented")
}
func (UnimplementedShopServiceServer) ListMyShopOrders(context.Context, *ListMyShopOrdersRequest) (*ListMyShopOrdersReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMyShopOrders not implemented")
}
func (UnimplementedShopServiceServer) MockPayShopOrder(context.Context, *MockPayShopOrderRequest) (*MockPayShopOrderReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MockPayShopOrder not implemented")
}
func (UnimplementedShopServiceServer) ListMyUnifiedOrders(context.Context, *ListMyUnifiedOrdersRequest) (*ListMyUnifiedOrdersReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMyUnifiedOrders not implemented")
}
func (UnimplementedShopServiceServer) ListMyFrequentStores(context.Context, *ListMyFrequentStoresRequest) (*ListMyFrequentStoresReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMyFrequentStores not implemented")
}
func (UnimplementedShopServiceServer) GetMyUnifiedOrder(context.Context, *GetMyUnifiedOrderRequest) (*GetMyUnifiedOrderReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMyUnifiedOrder not implemented")
}
func (UnimplementedShopServiceServer) MockPayUnifiedOrder(context.Context, *MockPayUnifiedOrderRequest) (*MockPayUnifiedOrderReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MockPayUnifiedOrder not implemented")
}
func (UnimplementedShopServiceServer) mustEmbedUnimplementedShopServiceServer() {}

// UnsafeShopServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShopServiceServer will
// result in compilation errors.
type UnsafeShopServiceServer interface {
	mustEmbedUnimplementedShopServiceServer()
}

func RegisterShopServiceServer(s grpc.ServiceRegistrar, srv ShopServiceServer) {
	s.RegisterService(&ShopService_ServiceDesc, srv)
}

func _ShopService_ListProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).ListProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_ListProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).ListProducts(ctx, req.(*ListProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_GetProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).GetProduct(ctx, req.(*GetProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_ListDeliveryAddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDeliveryAddressesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).ListDeliveryAddresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_ListDeliveryAddresses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).ListDeliveryAddresses(ctx, req.(*ListDeliveryAddressesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_CreateDeliveryAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeliveryAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).CreateDeliveryAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_CreateDeliveryAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).CreateDeliveryAddress(ctx, req.(*CreateDeliveryAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_UpdateDeliveryAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDeliveryAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).UpdateDeliveryAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_UpdateDeliveryAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).UpdateDeliveryAddress(ctx, req.(*UpdateDeliveryAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_DeleteDeliveryAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDeliveryAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).DeleteDeliveryAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_DeleteDeliveryAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).DeleteDeliveryAddress(ctx, req.(*DeleteDeliveryAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_SetDefaultDeliveryAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDefaultDeliveryAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).SetDefaultDeliveryAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_SetDefaultDeliveryAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).SetDefaultDeliveryAddress(ctx, req.(*SetDefaultDeliveryAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_CreateDepositHold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDepositHoldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).CreateDepositHold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_CreateDepositHold_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).CreateDepositHold(ctx, req.(*CreateDepositHoldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_GetMyDepositHold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyDepositHoldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).GetMyDepositHold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_GetMyDepositHold_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).GetMyDepositHold(ctx, req.(*GetMyDepositHoldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_CreateShopOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShopOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).CreateShopOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_CreateShopOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).CreateShopOrder(ctx, req.(*CreateShopOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_ListMyShopOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyShopOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).ListMyShopOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_ListMyShopOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).ListMyShopOrders(ctx, req.(*ListMyShopOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_MockPayShopOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MockPayShopOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).MockPayShopOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_MockPayShopOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).MockPayShopOrder(ctx, req.(*MockPayShopOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_ListMyUnifiedOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyUnifiedOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).ListMyUnifiedOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_ListMyUnifiedOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).ListMyUnifiedOrders(ctx, req.(*ListMyUnifiedOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_ListMyFrequentStores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyFrequentStoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).ListMyFrequentStores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_ListMyFrequentStores_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).ListMyFrequentStores(ctx, req.(*ListMyFrequentStoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_GetMyUnifiedOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyUnifiedOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).GetMyUnifiedOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_GetMyUnifiedOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).GetMyUnifiedOrder(ctx, req.(*GetMyUnifiedOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopService_MockPayUnifiedOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MockPayUnifiedOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopServiceServer).MockPayUnifiedOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopService_MockPayUnifiedOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopServiceServer).MockPayUnifiedOrder(ctx, req.(*MockPayUnifiedOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShopService_ServiceDesc is the grpc.ServiceDesc for ShopService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShopService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auction.service.v1.ShopService",
	HandlerType: (*ShopServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListProducts",
			Handler:    _ShopService_ListProducts_Handler,
		},
		{
			MethodName: "GetProduct",
			Handler:    _ShopService_GetProduct_Handler,
		},
		{
			MethodName: "ListDeliveryAddresses",
			Handler:    _ShopService_ListDeliveryAddresses_Handler,
		},
		{
			MethodName: "CreateDeliveryAddress",
			Handler:    _ShopService_CreateDeliveryAddress_Handler,
		},
		{
			MethodName: "UpdateDeliveryAddress",
			Handler:    _ShopService_UpdateDeliveryAddress_Handler,
		},
		{
			MethodName: "DeleteDeliveryAddress",
			Handler:    _ShopService_DeleteDeliveryAddress_Handler,
		},
		{
			MethodName: "SetDefaultDeliveryAddress",
			Handler:    _ShopService_SetDefaultDeliveryAddress_Handler,
		},
		{
			MethodName: "CreateDepositHold",
			Handler:    _ShopService_CreateDepositHold_Handler,
		},
		{
			MethodName: "GetMyDepositHold",
			Handler:    _ShopService_GetMyDepositHold_Handler,
		},
		{
			MethodName: "CreateShopOrder",
			Handler:    _ShopService_CreateShopOrder_Handler,
		},
		{
			MethodName: "ListMyShopOrders",
			Handler:    _ShopService_ListMyShopOrders_Handler,
		},
		{
			MethodName: "MockPayShopOrder",
			Handler:    _ShopService_MockPayShopOrder_Handler,
		},
		{
			MethodName: "ListMyUnifiedOrders",
			Handler:    _ShopService_ListMyUnifiedOrders_Handler,
		},
		{
			MethodName: "ListMyFrequentStores",
			Handler:    _ShopService_ListMyFrequentStores_Handler,
		},
		{
			MethodName: "GetMyUnifiedOrder",
			Handler:    _ShopService_GetMyUnifiedOrder_Handler,
		},
		{
			MethodName: "MockPayUnifiedOrder",
			Handler:    _ShopService_MockPayUnifiedOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auction/service/v1/shop.proto",
}
