apiVersion: v1
kind: Service
metadata: {name: index-es}
spec:
  selector: {app.kubernetes.io/name: index-es}
  ports: [{name: operations, port: 18088, targetPort: operations}]
---
apiVersion: v1
kind: Service
metadata: {name: index-pgvector}
spec:
  selector: {app.kubernetes.io/name: index-pgvector}
  ports: [{name: operations, port: 18089, targetPort: operations}]
---
apiVersion: v1
kind: Service
metadata: {name: search-reconciler}
spec:
  selector: {app.kubernetes.io/name: search-reconciler}
  ports: [{name: operations, port: 18090, targetPort: operations}]
