bind 0.0.0.0
protected-mode no
port 6379

appendonly yes
appendfsync everysec
min-replicas-to-write 1
min-replicas-max-lag 10
maxmemory 256mb
maxmemory-policy noeviction
stop-writes-on-bgsave-error yes
repl-diskless-sync yes
repl-diskless-sync-delay 5
replica-read-only yes
