-- Deprecated compatibility marker.
--
-- The executable schema is owned exclusively by the paired, checksummed files in
-- deploy/mysql/migrations/*.up.sql and *.down.sql. Apply them with:
--
--   go run ./app/auction/service/cmd/migrate --dsn "$AUCTION_MYSQL_DSN" up
--
-- Do not add CREATE/ALTER statements to this file.
